import { kimberleyBookmarks, kimberleyDirection, kimberleyIdeas } from './kimberleyData.js'
import { flightIdeas } from './flightData.js'
import { waDeeperBookmarks, waDeeperDirection, waDeeperIdeas, waSuppliedGalleries } from './waDeeperData.js'

const asset = (name) => `${import.meta.env.BASE_URL}images/${name}`

const galleryImage = (id, file, caption, credit, license, sourceUrl) => ({
  id,
  src: asset(file),
  caption,
  credit,
  license,
  sourceUrl,
})

export const statusLabels = {
  included: 'Include',
  maybe: 'Maybe',
  excluded: 'Exclude',
}

const knownAreaColors = new Map([
  ['Flights & transfers', 'flight'],
  ['Perth & Western Australia', 'ochre'],
  ['The Kimberley', 'coral'],
  ['Tasmania', 'violet'],
  ['Sydney & New South Wales', 'blue'],
  ['Melbourne & Victoria', 'green'],
])
const fallbackAreaColors = ['green', 'ochre', 'violet', 'blue', 'coral']

export function ideaDisplayColor(idea) {
  if (idea?.kind === 'flight') return 'flight'
  const area = idea?.area || idea?.region || 'Other ideas'
  if (knownAreaColors.has(area)) return knownAreaColors.get(area)
  const hash = Array.from(area).reduce((total, character) => total + character.charCodeAt(0), 0)
  return fallbackAreaColors[hash % fallbackAreaColors.length]
}

export const seedIdeas = [
  {
    id: 'perth', name: 'Perth pause', region: 'Western Australia', area: 'Perth & Western Australia',
    summary: 'Kings Park, the Swan River and an easy arrival day.', days: 3, status: 'included', color: 'green',
    image: asset('perth.jpg'), coordinates: [115.8605, -31.9505], mapLabel: 'Perth',
    highlights: ['Kings Park at sunset', 'Swan River and Indian Ocean light', 'Keep the city stay deliberately brief'],
    note: 'Useful as a first-night landing and a buffer before or after the South West drive.',
    tradeoffs: 'Extra Perth nights make the long-haul arrival gentler, but compete directly with the South West road trip.',
    season: 'Late October is spring: generally mild, with longer daylight and some chance of showers.',
    rationale: 'Three days gives the long-haul arrival breathing room plus a useful outdoor Perth day before the road trip.',
    gallery: [galleryImage('perth-skyline', 'perth.jpg', 'Perth skyline', 'Robert Young', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Perth_skyline.jpg')],
  },
  {
    id: 'margaret-river', name: 'Margaret River & the Capes', region: 'South West WA', area: 'Perth & Western Australia',
    summary: 'Capes, caves, surf coast and karri forest.', days: 3, status: 'included', color: 'ochre',
    image: asset('margaret-river.jpg'), coverImageId: 'margaret-coast', coordinates: [115.073, -33.953], mapLabel: 'Margaret River',
    highlights: ['Cape Naturaliste and Cape Leeuwin', 'Caves and exposed coast', 'Boranup forest and spring wildflowers'],
    note: 'Use food and wine mainly as weather-day options; the scenery-led route is the two capes, caves and Boranup forest.',
    tradeoffs: 'A single base is easy; two bases reduce backtracking but add a packing day.',
    season: 'Spring suits coastal walks and wildflowers, though ocean weather can turn quickly.',
    rationale: 'Three days is still selective, but gives the two capes, a cave and Boranup forest enough room without turning the trip into a food-and-wine tour.',
    gallery: [
      galleryImage('boranup', 'boranup-forest.jpg', 'Karri forest at Boranup', 'Paulkyranc', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Karri_trees_-_Boranup_Forest_01.jpg'),
      galleryImage('margaret-coast', 'margaret-river.jpg', 'Indian Ocean coast near Margaret River', 'Wikimedia Commons contributor', 'See source page', 'https://commons.wikimedia.org/wiki/File:2016_Margaret_River_Australia_-_indian_ocean.jpg'),
    ],
  },
  {
    id: 'southern-forests', name: 'Pemberton & Walpole', region: 'South West WA', area: 'Perth & Western Australia',
    summary: 'Giant karri, forest drives and the Valley of the Giants.', days: 2, status: 'included', color: 'ochre',
    image: asset('boranup-forest.jpg'), coverImageId: 'southern-karri', coordinates: [116.05, -34.45], mapLabel: 'Pemberton & Walpole',
    highlights: ['Pemberton’s giant karri country', 'Walpole and the Valley of the Giants', 'Forest drives between the two bases'],
    note: 'This separates the forest leg from Denmark and Albany’s granite coast, making the South West read as a journey rather than an out-and-back.',
    tradeoffs: 'Two days is a purposeful transit through the forests; extra walks or a slower stay would need a third day.',
    season: 'Spring is lush and cool in the forest; allow for rain and check tree-top-walk access.',
    rationale: 'Two calendar days cover the scenic forest progression from Pemberton to Walpole before the route reaches Denmark.',
    gallery: [
      galleryImage('albany-coast', 'albany-coast.jpg', 'Coast near Albany', 'CSIRO', 'CC BY 3.0', 'https://commons.wikimedia.org/wiki/File:CSIRO_ScienceImage_2482_Coast_near_Albany_Western_Australia.jpg'),
      galleryImage('southern-karri', 'boranup-forest.jpg', 'Karri forest character', 'Paulkyranc', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Karri_trees_-_Boranup_Forest_01.jpg'),
    ],
  },
  {
    id: 'wa-denmark-albany', name: 'Denmark & Albany', region: 'Great Southern WA', area: 'Perth & Western Australia',
    summary: 'Turquoise coves, granite headlands and Albany’s exposed Southern Ocean coast.', days: 3, status: 'excluded', color: 'ochre',
    image: asset('greens-pool.jpg'), coverImageId: 'greens-pool', coordinates: [117.32, -35.01], mapLabel: 'Denmark & Albany', mapGroup: 'Western Australia',
    highlights: ['Greens Pool and Elephant Rocks', 'Torndirrup’s granite coast and blowholes', 'Albany viewpoints and sheltered bays'],
    note: 'Use Denmark for the calmer coves, then progress east to Albany for the bigger Southern Ocean landscapes.',
    tradeoffs: 'Three days avoids rushing both coastlines, but the return to Perth still needs a deliberately planned final drive.',
    season: 'November can be cool, windy and changeable; keep the most exposed headlands flexible.',
    rationale: 'Three calendar days turns Denmark and Albany into a coherent coastal module rather than incidental stops on a forest leg.',
    gallery: [galleryImage('greens-pool', 'greens-pool.jpg', 'Greens Pool, William Bay National Park', 'BaroBert', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Greens_Pool,_William_Bay,_Denmark_WA.jpg')],
  },
  {
    id: 'wa-bremer-fitzgerald', name: 'Bremer Bay & Fitzgerald River', region: 'Great Southern WA', area: 'Perth & Western Australia',
    summary: 'A remote coastal and botanical detour between Albany and Esperance.', days: 1, status: 'excluded', color: 'ochre',
    image: asset('fitzgerald-river.jpg'), coverImageId: 'fitzgerald-river', coordinates: [119.45, -34.15], mapLabel: 'Bremer & Fitzgerald', mapGroup: 'Western Australia',
    highlights: ['Fitzgerald River ranges and coastal heath', 'Bremer Bay headlands', 'A scenic bridge toward Esperance'],
    note: 'Keep this as an optional route-shaper rather than adding it on top of the 28-day plan.',
    tradeoffs: 'One day is a scenic transit; two days would be preferable for walking or weather resilience.',
    season: 'Spring wildflowers can be excellent, but distances and exposed roads require an early start and current park checks.',
    rationale: 'Include it only in the Esperance version, where it breaks the Albany–Esperance drive with a genuinely different landscape.',
    gallery: [galleryImage('fitzgerald-river', 'fitzgerald-river.jpg', 'Fitzgerald River National Park toward Thumb Peak', 'Bradley Hiller', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Fitzgerald_River_National_Park,_Western_Australia._Looking_North_East_towards_Thumb_Peak.jpg')],
  },
  {
    id: 'wa-hyden-return', name: 'Hyden inland return', region: 'Western Australia', area: 'Perth & Western Australia',
    summary: 'Wave Rock and an inland alternative for the long return toward Perth.', days: 1, status: 'excluded', color: 'ochre',
    image: asset('wave-rock.jpg'), coverImageId: 'wave-rock', coordinates: [118.865, -32.449], mapLabel: 'Hyden', mapGroup: 'Western Australia',
    highlights: ['Wave Rock', 'A change from the south-coast landscapes', 'Potential overnight break on the Perth return'],
    note: 'Useful only if the inland geometry improves the chosen route; it should replace another day, not extend the trip.',
    tradeoffs: 'Adds variety but also long, sparse-road driving and is less compelling than the coast if time is tight.',
    season: 'Warm spring days are possible; carry water and check fuel and road conditions.',
    rationale: 'A one-day inland return option to compare against flying or driving directly from Albany or Esperance.',
    gallery: [galleryImage('wave-rock', 'wave-rock.jpg', 'Wave Rock near Hyden', 'Brian W. Schaller', 'Free Art License', 'https://commons.wikimedia.org/wiki/File:A198,_Hyden,_Western_Australia,_Wave_Rock,_2007.JPG')],
  },
  {
    id: 'wa-tas-transit', name: 'Perth → Hobart flight', routeFrom: 'Perth', routeTo: 'Hobart', kind: 'flight', region: 'Flight', area: 'Flights & transfers', mapGroup: 'Flights',
    summary: 'A one-day domestic transfer from the WA road trip to Tasmania.', days: 1, status: 'excluded', color: 'flight',
    image: '', coordinates: [147.3272, -42.8821], mapLabel: 'Perth → Hobart', gallery: [],
    note: 'This is intentionally a visible itinerary card: the route is only realistic if the final WA drive, car return and flight are allowed for.',
    tradeoffs: 'A same-day chain may be tiring; a Perth airport night is the safer fallback if flight timings do not align.',
    season: 'Check the actual Perth–Hobart schedule before fixing accommodation or car returns.',
    rationale: 'One calendar day prevents the WA-to-Tasmania seam from disappearing between scenic cards.',
    highlights: ['Return the WA hire car', 'Allow for airport and baggage time', 'Collect the Tasmania car after arrival'],
  },
  {
    id: 'esperance', name: 'Esperance extension', region: 'Western Australia', area: 'Perth & Western Australia',
    summary: 'Cape Le Grand beaches and a long overland commitment.', days: 3, status: 'included', color: 'blue',
    image: asset('lucky-bay.jpg'), coordinates: [121.888, -33.861], mapLabel: 'Esperance',
    highlights: ['Cape Le Grand', 'Lucky Bay', 'Beautiful, but adds substantial road time'],
    note: 'Worth comparing against an eastern-state module: it reduces flying but makes the WA road trip much longer.',
    tradeoffs: 'The scenery is exceptional; the cost is roughly two demanding transit days unless you fly one leg.',
    season: 'Spring is attractive but exposed beaches can still be cool and windy.',
    rationale: 'Three days is a tight but workable module only if the long approach and onward route are planned carefully.',
    gallery: [galleryImage('lucky-bay', 'lucky-bay.jpg', 'Lucky Bay, Cape Le Grand National Park', 'DaHuzyBru', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Lucky_Bay,_Cape_Le_Grand_National_Park,_January_2025_01.jpg')],
  },
  {
    id: 'tas-hobart', name: 'Hobart & kunanyi', region: 'Tasmania', area: 'Tasmania',
    summary: 'Mountain viewpoints, waterfront light and a gentle landing.', days: 2, status: 'included', color: 'violet',
    image: asset('hobart-panorama.jpg'), coverImageId: 'hobart-panorama', coordinates: [147.3272, -42.8821], mapLabel: 'Hobart',
    highlights: ['kunanyi / Mount Wellington', 'Mount Field as a weather-flex landscape day', 'Waterfront, Salamanca and Battery Point on foot'],
    timestamps: ['00:36:46', '00:38:14', '00:38:44'],
    note: 'The video’s final Hobart section works well as the start of an anti-clockwise island loop.',
    tradeoffs: 'Two nights keeps the city compact; MONA, Bruny Island or a weather buffer would justify another.',
    season: 'November can deliver four seasons in a day; kunanyi may be much colder than the waterfront.',
    rationale: 'Two nights gives an arrival afternoon and one landscape-led Hobart day before the peninsula.',
    gallery: [
      galleryImage('hobart-panorama', 'hobart-panorama.jpg', 'Hobart from kunanyi / Mount Wellington', 'JJ Harrison', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Hobart_from_Mount_Wellington_Panorama_1.jpg'),
      galleryImage('hobart-salamanca', 'tas-hobart-salamanca.jpg', 'Salamanca Place with kunanyi behind', 'Cheng Fei', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:Hobart_Tasmania_Salamanca_Place.jpg'),
    ],
  },
  {
    id: 'tas-peninsula', name: 'Tasman Peninsula', region: 'Tasmania', area: 'Tasmania',
    summary: 'Sea cliffs, arches, caves and wave-cut rock platforms.', days: 2, status: 'included', color: 'violet',
    image: asset('tasman-cliffs.jpg'), coordinates: [147.850, -43.147], mapLabel: 'Tasman Peninsula',
    highlights: ['Tasman Arch and the Blow Hole', 'Remarkable Cave and Maingon Bay', 'Tessellated Pavement or a Cape Hauy walk'],
    timestamps: ['00:00:44', '00:01:43', '00:02:20', '00:03:45'],
    note: 'The source video opens with four close-together geological stops; a second day allows a real cliff walk rather than only viewpoints.',
    tradeoffs: 'A Hobart day trip avoids moving hotels, but staying on the peninsula creates calmer light and walking time.',
    season: 'Exposed cliffs are weather-dependent; keep a sheltered or heritage fallback.',
    rationale: 'One calendar day is a focused viewpoints drive via the Tessellated Pavement, Tasman Arch and Devil’s Kitchen; allow two if Port Arthur or Cape Hauy is a priority.',
    gallery: [galleryImage('cape-huay', 'tasman-cliffs.jpg', 'Sea cliffs at Cape Huay, Tasman National Park', 'Mooonrise', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:The_spectacular_sea_cliffs_of_Cape_Huay,_Tasman_National_Park,_Tasmania.jpg')],
  },
  {
    id: 'tas-maria', name: 'Maria Island', region: 'Tasmania', area: 'Tasmania',
    summary: 'Painted Cliffs, wildlife and a car-free island day.', days: 1, status: 'excluded', color: 'violet',
    image: asset('maria-island.jpg'), coverImageId: 'maria-painted-cliffs', coordinates: [148.05, -42.62], mapLabel: 'Maria Island',
    highlights: ['Painted Cliffs', 'Wombats and open coastal scenery', 'Ferry from Triabunna'],
    note: 'A strong scenery-led alternative between Hobart and Freycinet, but it needs to replace another east-coast day rather than extend the trip.',
    tradeoffs: 'The ferry timetable and weather reduce flexibility, and the island deserves more than a rushed half-day.',
    season: 'Spring wildlife and walking can be excellent; check ferry capacity and exposed-coast conditions.',
    rationale: 'Keep as an optional one-day swap for travellers who value a car-free island landscape over a longer Bay of Fires or Hobart stay.',
    gallery: [galleryImage('maria-painted-cliffs', 'maria-island.jpg', 'Painted Cliffs, Maria Island', 'JJ Harrison', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Painted_Cliffs.jpg')],
  },
  {
    id: 'tas-east', name: 'Freycinet & Bicheno', region: 'Tasmania', area: 'Tasmania',
    summary: 'Pink granite peaks, Wineglass Bay and small coves.', days: 2, status: 'included', color: 'violet',
    image: asset('wineglass-bay.jpg'), coordinates: [148.287, -42.123], mapLabel: 'Freycinet',
    highlights: ['Wineglass Bay Lookout', 'Honeymoon Bay and Friendly Beaches', 'Bicheno blowhole and coastal rocks'],
    timestamps: ['00:05:30', '00:07:31', '00:08:07', '00:10:04'],
    note: 'A compact but scenic section of the anti-clockwise circuit, with the longer walk chosen by weather.',
    tradeoffs: 'Two nights is enough for the lookout and coast; a full Wineglass circuit or slower Bicheno stay needs three.',
    season: 'Longer spring days help; wind can decide whether the exposed walk or sheltered coves win.',
    rationale: 'Two calendar days preserve the Wineglass Bay and Bicheno progression without reducing Freycinet to a roadside stop.',
    gallery: [galleryImage('wineglass', 'wineglass-bay.jpg', 'Wineglass Bay from the lookout', 'JJ Harrison', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Wineglass_Bay_from_Lookout.jpg')],
  },
  {
    id: 'tas-bay-fires', name: 'Bay of Fires', region: 'Tasmania', area: 'Tasmania',
    summary: 'White sand, turquoise water and orange-lichen granite.', days: 2, status: 'included', color: 'violet',
    image: asset('bay-of-fires.jpg'), coordinates: [148.279, -41.282], mapLabel: 'Bay of Fires',
    highlights: ['Skeleton Bay', 'Cozy Corner', 'The Gardens and Binalong Bay'],
    timestamps: ['00:11:02', '00:13:36', '00:16:39'],
    note: 'This is deliberately its own card: the north-east coast deserves a decision separate from Freycinet.',
    tradeoffs: 'Beautiful in clear weather, but a long coastal arc if the west and north-west are also included.',
    season: 'Late spring brings long evenings; water and wind temperatures can still feel cool.',
    rationale: 'One calendar day is a selective scenic progression through the strongest granite coves and orange-lichen shoreline.',
    gallery: [galleryImage('bay-fires', 'bay-of-fires.jpg', 'Granite boulders and coast at Bay of Fires', 'Diego Delso', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Bay_of_Fires-02.jpg')],
  },
  {
    id: 'tas-north', name: 'Launceston', region: 'Tasmania', area: 'Tasmania',
    summary: 'Cataract Gorge and a practical northern Tasmania pause.', days: 1, status: 'included', color: 'violet',
    image: asset('cataract-gorge.jpg'), coordinates: [147.1441, -41.4332], mapLabel: 'Launceston',
    highlights: ['Cataract Gorge', 'Tamar Valley viewpoints if time allows', 'A low-effort bridge between the east coast and Cradle Mountain'],
    timestamps: ['00:18:41', '00:20:30'],
    note: 'Narawntapu remains a possible detour, but it is not part of this one-day primary plan.',
    tradeoffs: 'The city pause is practical rather than spectacular; keep it short before Cradle Mountain.',
    season: 'Spring wildlife and coastal heath are strengths; avoid dusk driving after wildlife viewing.',
    rationale: 'One calendar day provides a useful reset and breaks the drive from the north-east coast to Cradle Mountain.',
    gallery: [galleryImage('cataract-gorge', 'cataract-gorge.jpg', 'Cataract Gorge in spring', 'Thomas Calderbank', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:Cataract_Gorge,_Launceston_in_spring.jpg')],
  },
  {
    id: 'tas-stanley', name: 'Stanley & the North West', region: 'Tasmania', area: 'Tasmania',
    summary: 'The Nut, Bass Strait headlands and little penguins.', days: 2, status: 'included', color: 'violet',
    image: asset('stanley-nut.jpg'), coordinates: [145.297, -40.760], mapLabel: 'Stanley',
    highlights: ['Walk or chairlift up The Nut', 'Little penguins after dark', 'A broad north-west arc toward Cradle Mountain'],
    timestamps: ['00:22:11', '00:23:55'],
    note: 'The source route continues west through Stanley, but this is the easiest northern module to remove when time is tight.',
    tradeoffs: 'A distinctive landscape and strong route shape, paid for with a substantial detour and another hotel change.',
    season: 'Bass Strait weather is exposed; the penguin experience is after dark, when wildlife makes driving riskier.',
    rationale: 'Two nights makes the detour worthwhile and avoids arriving and leaving in the dark.',
    gallery: [galleryImage('stanley-nut', 'stanley-nut.jpg', 'Stanley and The Nut', 'Taspictures', 'CC0', 'https://commons.wikimedia.org/wiki/File:StanleyAndNut.jpg')],
  },
  {
    id: 'tas-highlands', name: 'Cradle Mountain', region: 'Tasmania', area: 'Tasmania',
    summary: 'Glacial lakes, alpine ridges, rainforest and wombats.', days: 3, status: 'included', color: 'violet',
    image: asset('cradle-boatshed.jpg'), coordinates: [145.949, -41.685], mapLabel: 'Cradle Mt',
    highlights: ['Ronny Creek wombats', 'Dove Lake Circuit', 'Marion’s Lookout when conditions cooperate'],
    timestamps: ['00:28:50', '00:30:41'],
    note: 'Keep weather flexibility here; alpine conditions can change quickly even in spring.',
    tradeoffs: 'Three nights protects one good walking day, but reduces the number of coast modules that fit comfortably.',
    season: 'Snow, rain, wind and clear sun are all plausible. Treat the higher walk as weather-dependent.',
    rationale: 'Three nights provides two walk opportunities and makes one bad-weather day much less damaging.',
    gallery: [
      galleryImage('cradle-boatshed', 'cradle-boatshed.jpg', 'Dove Lake boatshed and Cradle Mountain', 'Thennicke', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Boat_shed_and_Cradle_Mountain_at_Dove_Lake,_Tas.jpg'),
      galleryImage('cradle-dove', 'cradle-mountain.jpg', 'Cradle Mountain over Dove Lake', 'BennyG3255', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Cradle_Mountain_over_Dove_Lake,_Tasmania.jpg'),
    ],
  },
  {
    id: 'tas-west', name: 'Strahan & the Wild West', region: 'Tasmania', area: 'Tasmania',
    summary: 'Rainforest, dunes, wild ocean and the Lyell Highway.', days: 1, status: 'included', color: 'violet',
    image: asset('strahan.jpg'), coordinates: [145.327, -42.153], mapLabel: 'Strahan',
    highlights: ['Gordon River cruise', 'Strahan waterfront', 'Ocean Beach, Henty Dunes and Nelson Falls'],
    timestamps: ['00:33:18', '00:35:06', '00:36:06'],
    note: 'The western section supplies the strongest landscape contrast in the island loop and the slowest roads.',
    tradeoffs: 'It adds rain risk and winding driving; removing it shortens Tasmania substantially but weakens the loop.',
    season: 'Expect wet and changeable conditions; the rainforest and waterfalls are still rewarding in poor weather.',
    rationale: 'Two calendar days allow a Gordon River cruise as the principal highlight plus a concise west-coast landscape circuit.',
    gallery: [galleryImage('strahan', 'strahan.jpg', 'Strahan on Tasmania’s west coast', 'Timox14', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Strahan,_Tasmania.jpg')],
  },
  {
    id: 'tas-lake-st-clair-return', name: 'Lake St Clair return', region: 'Tasmania', area: 'Tasmania',
    summary: 'Lake St Clair and the final scenic return toward Hobart.', days: 1, status: 'excluded', color: 'violet',
    image: asset('lake-st-clair.jpg'), coverImageId: 'lake-st-clair', coordinates: [146.16, -42.06], mapLabel: 'Lake St Clair',
    highlights: ['Lake St Clair shoreline', 'Nelson Falls or Franklin River stop', 'Make the return to Hobart explicit'],
    note: 'A visible relocation day from Strahan through the World Heritage highlands, finishing near Hobart for the Sydney flight.',
    tradeoffs: 'The Lyell Highway is scenic but slow; avoid loading it with too many walks before an onward flight.',
    season: 'Highland weather can change quickly even in November; check road conditions and leave daylight margin.',
    rationale: 'One calendar day closes the Tasmania loop honestly and makes Lake St Clair part of the journey rather than a hidden drive.',
    gallery: [galleryImage('lake-st-clair', 'lake-st-clair.jpg', 'Lake St Clair', 'Diego Delso', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Parque_Nacional_Lago_St_Clair-Tasmania-Australia01.JPG')],
  },
  {
    id: 'vic-melbourne', name: 'Melbourne & the Bay', region: 'Victoria', area: 'Melbourne & Victoria',
    summary: 'A gentle city pause framed by river, bay and gardens.', days: 2, status: 'excluded', color: 'coral',
    image: asset('melbourne.jpg'), coordinates: [144.9631, -37.8136], mapLabel: 'Melbourne',
    highlights: ['Royal Botanic Gardens and the Yarra', 'Port Phillip Bay foreshore', 'Useful flight gateway rather than the trip’s scenic headline'],
    note: 'Keep this as a low-intensity hinge between flights and the two stronger Victorian landscape modules.',
    tradeoffs: 'A useful recovery stop, but city days compete with the Great Ocean Road, Wilsons Prom and Tasmania.',
    season: 'Late spring is mild but famously changeable; retain wet-weather flexibility.',
    rationale: 'Two nights allows an arrival day and one outdoor city day before or after a road loop.',
    gallery: [galleryImage('melbourne-yarra', 'melbourne.jpg', 'Melbourne and the Yarra River', 'Donaldytong', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Melbourne_Yarra_River.jpg')],
  },
  {
    id: 'vic-great-ocean', name: 'Great Ocean Road & Otways', region: 'Victoria', area: 'Melbourne & Victoria',
    summary: 'Surf coast, rainforest, waterfalls and limestone stacks.', days: 3, status: 'excluded', color: 'coral',
    image: asset('great-ocean-road.jpg'), coordinates: [143.105, -38.665], mapLabel: '12 Apostles',
    highlights: ['Great Otway rainforest and waterfalls', 'Twelve Apostles and Gibson Steps', 'Loch Ard Gorge and the Shipwreck Coast'],
    note: 'Visit Victoria’s official touring route recommends three days; this is the strongest scenery-led Melbourne extension.',
    tradeoffs: 'A rewarding self-drive, but it duplicates some coastal drama already present in WA and Tasmania.',
    season: 'Spring offers green landscapes and waterfalls; wind and showers can obscure the limestone coast.',
    rationale: 'Three nights is the minimum that lets the Otways and Shipwreck Coast feel like a journey rather than a long day trip.',
    gallery: [galleryImage('twelve-apostles', 'great-ocean-road.jpg', 'Twelve Apostles, Port Campbell National Park', 'Dietmar Rabich', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Princetown_(AU),_Port_Campbell_National_Park,_Twelve_Apostles_--_2019_--_0969.jpg')],
  },
  {
    id: 'vic-prom', name: 'Wilsons Promontory', region: 'Victoria', area: 'Melbourne & Victoria',
    summary: 'Granite headlands, white beaches, forest and wildlife.', days: 2, status: 'excluded', color: 'coral',
    image: asset('wilsons-prom.jpg'), coordinates: [146.321, -39.030], mapLabel: 'Wilsons Prom',
    highlights: ['Squeaky Beach and Tidal River', 'Mount Oberon or Tidal Overlook', 'Wombats, kangaroos and spring wildflowers'],
    note: 'A stronger nature counterpoint to Melbourne than another urban day, but in the opposite direction to the Great Ocean Road.',
    tradeoffs: 'Excellent scenery; combining it with the Great Ocean Road creates two separate Melbourne road loops.',
    season: 'Spring wildflowers are a strength; coastal wind and walking conditions remain changeable.',
    rationale: 'Two nights supports one major walk and one coast day without turning it into a rushed return drive.',
    gallery: [galleryImage('wilsons-squeaky', 'wilsons-prom.jpg', 'Squeaky Beach at sunset, Wilsons Promontory', 'Iwanttobeanomad', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Wilsons_Promontory_National_Park_-_Squeaky_Beach_sunset.jpg')],
  },
  {
    id: 'nsw-sydney', name: 'Sydney Harbour & Coast', region: 'New South Wales', area: 'Sydney & New South Wales',
    summary: 'Harbour headlands, ferries, sandstone and ocean cliffs.', days: 2, status: 'included', color: 'blue',
    image: asset('sydney-harbour.jpg'), coordinates: [151.2093, -33.8688], mapLabel: 'Sydney',
    highlights: ['Harbour ferry and headland views', 'A Bondi–Coogee or Spit–Manly section', 'Convenient final base before the UK flight'],
    note: 'Sydney earns its place as scenery as well as logistics: harbour water, coastal sandstone and beaches can fill the short stay.',
    tradeoffs: 'Two nights is efficient for departure; three reduces the risk of the city becoming only an airport buffer.',
    season: 'Late spring is well suited to coastal walking, with sun protection and a wet-weather alternative still needed.',
    rationale: 'Two nights creates one full scenic day and positions the likely long-haul departure without another domestic connection.',
    gallery: [galleryImage('sydney-harbour', 'sydney-harbour.jpg', 'Sydney Harbour', 'Shiv Travelogue', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Sydney_Shot.jpg')],
  },
  {
    id: 'nsw-blue', name: 'Blue Mountains', region: 'New South Wales', area: 'Sydney & New South Wales',
    summary: 'Sandstone escarpments, waterfalls and eucalyptus valleys.', days: 1, status: 'included', color: 'blue',
    image: asset('blue-mountains.jpg'), coordinates: [150.3119, -33.7125], mapLabel: 'Blue Mountains',
    highlights: ['Govetts Leap and Grose Valley', 'Evans Lookout', 'Wentworth Falls'],
    note: 'Use this as a scenery-first Sydney day trip, returning to the city rather than adding another hotel base.',
    tradeoffs: 'A single day is weather-sensitive; an overnight would provide better light and resilience but costs a Sydney or Tasmania day.',
    season: 'Spring walking is attractive, though mist can conceal lookouts and bushfire alerts must be checked.',
    rationale: 'One calendar day gives the principal escarpment viewpoints while the Sydney base protects the UK departure.',
    gallery: [galleryImage('three-sisters', 'blue-mountains.jpg', 'Three Sisters, Blue Mountains National Park', 'Dietmar Rabich', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Blue_Mountains_National_Park_(AU),_Three_Sisters_--_2019_--_1987-9.jpg')],
  },
  {
    id: 'nsw-royal', name: 'Royal National Park', region: 'New South Wales', area: 'Sydney & New South Wales',
    summary: 'Coastal heath, cliffs, beaches and pockets of rainforest.', days: 2, status: 'excluded', color: 'blue',
    image: asset('royal-national-park.jpg'), coordinates: [151.056, -34.117], mapLabel: 'Royal NP',
    highlights: ['Coast Track or Curra Moors section', 'Wattamolla and coastal cliffs', 'Spring heathland wildflowers'],
    note: 'A nature-first Sydney add-on about an hour from the city, best kept optional beside the Blue Mountains.',
    tradeoffs: 'It adds another coast module; the Blue Mountains offers more contrast if only one Sydney side trip fits.',
    season: 'Spring wildflowers are a reason to go; check fire danger, track alerts and ocean conditions.',
    rationale: 'Two nights avoids attempting a major coastal walk between city traffic and a long-haul departure.',
    gallery: [galleryImage('royal-coast', 'royal-national-park.jpg', 'The Coast Walk, Royal National Park', 'Alex Proimos', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Bushland,_Royal_National_Park,_The_Coast_Walk,_NSW_Australia_(4045437811).jpg')],
  },
  ...waDeeperIdeas,
  ...kimberleyIdeas,
  ...flightIdeas,
].map((idea) => {
  const suppliedGallery = waSuppliedGalleries[idea.id] || []
  if (!suppliedGallery.length) return idea
  const gallery = [...(idea.gallery || []), ...suppliedGallery]
  const requestedCover = gallery.find((image) => image.id === idea.coverImageId)
  return { ...idea, gallery, image: requestedCover?.src || idea.image }
})

const directionPlan = (choices) => Object.fromEntries(seedIdeas.map((idea) => [idea.id, choices[idea.id] || ['excluded', idea.days]]))

export const scenarios = [
  { ...kimberleyDirection, plan: directionPlan(kimberleyDirection.choices), choices: undefined },
  {
    id: 'wa-tas-sydney', name: 'WA + Tasmania + Sydney', days: 28, pace: 'Full, scenery-led', transit: '2 domestic flights + WA and Tasmania road sections',
    image: asset('sydney-harbour.jpg'), summary: 'A realistic South West loop, Tasmania’s strongest landscapes and a Sydney departure buffer—all within 28 calendar days.',
    pros: ['Every relocation day is visible', 'Three days each for the Capes and Denmark–Albany coast', 'Sydney remains both a scenic finish and UK departure gateway'],
    order: ['perth', 'margaret-river', 'southern-forests', 'wa-denmark-albany', 'wa-tas-transit', 'tas-hobart', 'tas-peninsula', 'tas-east', 'tas-bay-fires', 'tas-north', 'tas-highlands', 'tas-west', 'tas-lake-st-clair-return', 'tas-sydney-transit', 'nsw-sydney', 'nsw-blue'],
    plan: directionPlan({ perth: ['included', 2], 'margaret-river': ['included', 3], 'southern-forests': ['included', 2], 'wa-denmark-albany': ['included', 3], 'wa-tas-transit': ['included', 1], 'tas-hobart': ['included', 2], 'tas-peninsula': ['included', 1], 'tas-east': ['included', 2], 'tas-bay-fires': ['included', 1], 'tas-north': ['included', 1], 'tas-highlands': ['included', 3], 'tas-west': ['included', 2], 'tas-lake-st-clair-return': ['included', 1], 'tas-sydney-transit': ['included', 1], 'nsw-sydney': ['included', 2], 'nsw-blue': ['included', 1] }),
  },
  {
    id: 'wa-esperance-tas-sydney', name: 'WA with Esperance + Tasmania highlights + Sydney', days: 28, pace: 'Driving-heavy, selective Tasmania', transit: '2 domestic flights + a long WA south-coast road trip',
    image: asset('lucky-bay.jpg'), summary: 'Keep Esperance by trimming Tasmania to its strongest highland and west-coast modules.',
    pros: ['Cape Le Grand stays in the trip', 'Bremer Bay breaks the eastward drive', 'Sydney still protects the UK departure'],
    order: ['perth', 'margaret-river', 'southern-forests', 'wa-denmark-albany', 'wa-bremer-fitzgerald', 'esperance', 'wa-tas-transit', 'tas-hobart', 'tas-peninsula', 'tas-east', 'tas-highlands', 'tas-west', 'tas-lake-st-clair-return', 'tas-sydney-transit', 'nsw-sydney', 'nsw-blue'],
    plan: directionPlan({ perth: ['included', 2], 'margaret-river': ['included', 2], 'southern-forests': ['included', 2], 'wa-denmark-albany': ['included', 3], 'wa-bremer-fitzgerald': ['included', 1], esperance: ['included', 3], 'wa-tas-transit': ['included', 1], 'tas-hobart': ['included', 2], 'tas-peninsula': ['included', 1], 'tas-east': ['included', 2], 'tas-highlands': ['included', 2], 'tas-west': ['included', 2], 'tas-lake-st-clair-return': ['included', 1], 'tas-sydney-transit': ['included', 1], 'nsw-sydney': ['included', 2], 'nsw-blue': ['included', 1] }),
  },
  {
    id: 'wa-tas', name: 'WA + full Tasmania', days: 28, pace: 'Varied, slower island loop', transit: '1 domestic flight + WA and Tasmania road sections',
    image: asset('cradle-boatshed.jpg'), summary: 'Use the extra time for Stanley and a less compressed anti-clockwise Tasmania circuit.',
    pros: ['Strongest Tasmania coverage', 'Uses every scenery module from the source notes', 'Only one domestic flight seam'],
    order: ['perth', 'margaret-river', 'southern-forests', 'wa-tas-transit', 'tas-hobart', 'tas-peninsula', 'tas-east', 'tas-bay-fires', 'tas-north', 'tas-stanley', 'tas-highlands', 'tas-west'],
    plan: directionPlan({ perth: ['included', 2], 'margaret-river': ['included', 4], 'southern-forests': ['included', 3], 'wa-tas-transit': ['included', 1], 'tas-hobart': ['included', 2], 'tas-peninsula': ['included', 2], 'tas-east': ['included', 2], 'tas-bay-fires': ['included', 2], 'tas-north': ['included', 2], 'tas-stanley': ['maybe', 2], 'tas-highlands': ['included', 3], 'tas-west': ['included', 4] }),
  },
  {
    id: 'wa-vic-sydney', name: 'WA + Victoria + Sydney', days: 28, pace: 'Three distinct road trips', transit: '2 domestic flights + separate Victoria drives',
    image: asset('great-ocean-road.jpg'), summary: 'Replace Tasmania with Esperance, Victoria’s two strongest coastal landscapes and a Sydney finish.',
    pros: ['No alpine Tasmania weather dependency', 'Great Ocean Road and Wilsons Prom are strong standalone modules', 'Sydney remains the departure gateway'],
    order: ['perth', 'margaret-river', 'southern-forests', 'perth-melbourne-transit', 'vic-melbourne', 'vic-great-ocean', 'vic-prom', 'melbourne-sydney-transit', 'nsw-sydney', 'nsw-blue', 'nsw-royal'],
    plan: directionPlan({ perth: ['included', 2], 'margaret-river': ['included', 4], 'southern-forests': ['included', 3], esperance: ['maybe', 4], 'perth-melbourne-transit': ['included', 1], 'vic-melbourne': ['included', 2], 'vic-great-ocean': ['included', 4], 'vic-prom': ['included', 3], 'melbourne-sydney-transit': ['included', 1], 'nsw-sydney': ['included', 3], 'nsw-blue': ['included', 2], 'nsw-royal': ['included', 1] }),
  },
  { ...waDeeperDirection, plan: directionPlan(waDeeperDirection.choices), choices: undefined },
]

export const flightNotes = [
  { id: 'london-perth', route: 'London → Perth', from: 'London', to: 'Perth', time: 'Long-haul · live search', detail: 'Compare one-ticket itineraries and leave the first day gentle after the overnight journey.', href: 'https://www.google.com/travel/flights?q=Flights%20from%20London%20to%20Perth%20October%202026', label: 'Search' },
  { id: 'perth-kununurra', route: 'Perth → Kununurra', from: 'Perth', to: 'Kununurra', time: 'Regional flight', detail: 'Confirm the late-October operating day before fixing the East Kimberley accommodation sequence.', href: 'https://www.google.com/travel/flights?q=Flights%20from%20Perth%20to%20Kununurra%20October%202026', label: 'Check dates' },
  { id: 'kununurra-perth', route: 'Kununurra → Perth', from: 'Kununurra', to: 'Perth', time: 'Regional flight', detail: 'Return the Kimberley hire car and allow a safe margin before any onward Perth or London connection; schedules may be less frequent late in the season.', href: 'https://www.google.com/travel/flights?q=Flights%20from%20Kununurra%20to%20Perth%20November%202026', label: 'Check dates' },
  { id: 'perth-hobart', route: 'Perth → Hobart', from: 'Perth', to: 'Hobart', time: 'Direct or one stop', detail: 'Direct service can be limited, so compare the exact date against connections via Melbourne.', href: 'https://www.google.com/travel/flights?q=Flights%20from%20Perth%20to%20Hobart%20November%202026', label: 'Check dates' },
  { id: 'perth-hobart-fallback', route: 'Perth → Melbourne → Hobart', from: 'Perth', to: 'Hobart', via: 'Melbourne', time: 'One-stop fallback', detail: 'A practical fallback if a direct day does not fit. Keep a generous connection on separate tickets.', href: 'https://www.google.com/travel/flights?q=Flights%20from%20Perth%20to%20Hobart%20via%20Melbourne%20November%202026', label: 'Compare' },
  { id: 'perth-melbourne', route: 'Perth → Melbourne', from: 'Perth', to: 'Melbourne', time: 'Domestic flight', detail: 'Use when Victoria follows WA; compare arriving early enough to avoid losing the following road-trip day.', href: 'https://www.google.com/travel/flights?q=Flights%20from%20Perth%20to%20Melbourne%20November%202026', label: 'Compare' },
  { id: 'perth-sydney', route: 'Perth → Sydney', from: 'Perth', to: 'Sydney', time: 'Domestic flight', detail: 'Shown when Sydney follows WA directly without Tasmania or Victoria.', href: 'https://www.google.com/travel/flights?q=Flights%20from%20Perth%20to%20Sydney%20November%202026', label: 'Compare' },
  { id: 'hobart-melbourne', route: 'Hobart → Melbourne', from: 'Hobart', to: 'Melbourne', time: 'Domestic flight', detail: 'Use when Victoria follows Tasmania; direct schedules are normally the cleanest seam.', href: 'https://www.google.com/travel/flights?q=Flights%20from%20Hobart%20to%20Melbourne%20November%202026', label: 'Compare' },
  { id: 'hobart-sydney', route: 'Hobart → Sydney', from: 'Hobart', to: 'Sydney', time: 'Domestic flight', detail: 'Positions the trip for a Sydney finish and likely UK departure.', href: 'https://www.google.com/travel/flights?q=Flights%20from%20Hobart%20to%20Sydney%20November%202026', label: 'Compare' },
  { id: 'melbourne-sydney', route: 'Melbourne → Sydney', from: 'Melbourne', to: 'Sydney', time: 'Domestic flight', detail: 'Usually more useful than driving when Sydney is the final short module before London.', href: 'https://www.google.com/travel/flights?q=Flights%20from%20Melbourne%20to%20Sydney%20November%202026', label: 'Compare' },
  { id: 'hobart-london', route: 'Hobart → London', from: 'Hobart', to: 'London', time: 'Long-haul · live search', detail: 'Compare through-tickets via an Australian or Asian hub; also test positioning to Melbourne or Sydney.', href: 'https://www.google.com/travel/flights?q=Flights%20from%20Hobart%20to%20London%20November%202026', label: 'Search' },
  { id: 'melbourne-london', route: 'Melbourne → London', from: 'Melbourne', to: 'London', time: 'Long-haul · live search', detail: 'Shown when the plan ends in Victoria; compare the whole itinerary rather than separate long-haul tickets.', href: 'https://www.google.com/travel/flights?q=Flights%20from%20Melbourne%20to%20London%20November%202026', label: 'Search' },
  { id: 'sydney-london', route: 'Sydney → London', from: 'Sydney', to: 'London', time: 'Likely return gateway · live search', detail: 'Compare through-fares and total elapsed time; protect the international departure with a final Sydney night.', href: 'https://www.google.com/travel/flights?q=Flights%20from%20Sydney%20to%20London%20November%202026', label: 'Search' },
  { id: 'perth-london', route: 'Perth → London', from: 'Perth', to: 'London', time: 'Long-haul · live search', detail: 'Shown when the plan currently ends in Western Australia.', href: 'https://www.google.com/travel/flights?q=Flights%20from%20Perth%20to%20London%20November%202026', label: 'Search' },
]

export const seedBookmarks = [
  ...kimberleyBookmarks,
  ...waDeeperBookmarks,
  { id: 'william-bay-parks', label: 'William Bay National Park', href: 'https://exploreparks.dbca.wa.gov.au/park/william-bay-national-park', category: 'Research', scope: 'Denmark & Albany', ideaIds: ['wa-denmark-albany'], note: 'Official Greens Pool, Elephant Rocks, access and construction information.', pinned: true },
  { id: 'fitzgerald-parks', label: 'Fitzgerald River National Park', href: 'https://exploreparks.dbca.wa.gov.au/park/fitzgerald-river-national-park', category: 'Research', scope: 'Bremer Bay / Fitzgerald River', ideaIds: ['wa-bremer-fitzgerald'], note: 'Official park access, walks, alerts and facilities.', pinned: false },
  { id: 'maria-parks', label: 'Maria Island and Painted Cliffs', href: 'https://parks.tas.gov.au/explore-our-parks/maria-island-national-park/painted-cliffs', category: 'Research', scope: 'Maria Island', ideaIds: ['tas-maria'], note: 'Official ferry, tide, safety and walking information.', pinned: false },
  { id: 'lake-st-clair-parks', label: 'Lake St Clair', href: 'https://parks.tas.gov.au/explore-our-parks/lake-st-clair', category: 'Research', scope: 'Lake St Clair', ideaIds: ['tas-lake-st-clair-return'], note: 'Official access, short walks, weather and visitor-centre information.', pinned: true },
  { id: 'tas-video', label: 'Tasmania source video', href: 'https://youtu.be/wC62ZLZgEDM', category: 'Research', scope: 'Tasmania', ideaIds: ['tas-hobart', 'tas-peninsula', 'tas-east', 'tas-bay-fires', 'tas-north', 'tas-stanley', 'tas-highlands', 'tas-west'], note: 'Source for the timestamped Tasmania place notes.', pinned: true },
  { id: 'tasman-parks', label: 'Tasman National Park', href: 'https://parks.tas.gov.au/explore-our-parks/tasman-national-park', category: 'Research', scope: 'Tasman Peninsula', ideaIds: ['tas-peninsula'], note: 'Official sea-cliff, walk, access and alert information.', pinned: true },
  { id: 'freycinet-parks', label: 'Freycinet National Park', href: 'https://parks.tas.gov.au/explore-our-parks/freycinet-national-park', category: 'Research', scope: 'Freycinet', ideaIds: ['tas-east'], note: 'Official park, walk and alert information.', pinned: true },
  { id: 'bay-fires-parks', label: 'Bay of Fires Conservation Area', href: 'https://parks.tas.gov.au/explore-our-parks/bay-of-fires-conservation-area', category: 'Research', scope: 'Bay of Fires', ideaIds: ['tas-bay-fires'], note: 'Official access, landscape and safety notes.', pinned: false },
  { id: 'narawntapu-parks', label: 'Narawntapu National Park', href: 'https://parks.tas.gov.au/explore-our-parks/narawntapu-national-park', category: 'Research', scope: 'Launceston / north', ideaIds: ['tas-north'], note: 'Official walking, wildlife and dusk-driving guidance.', pinned: false },
  { id: 'cradle-shuttle', label: 'Cradle Mountain shuttle', href: 'https://parks.tas.gov.au/explore-our-parks/cradle-mountain/cradle-mountain-shuttle-bus-information', category: 'Logistics', scope: 'Cradle Mountain', ideaIds: ['tas-highlands'], note: 'Seasonal access and shuttle operating details.', pinned: true },
  { id: 'franklin-parks', label: 'Franklin–Gordon Wild Rivers', href: 'https://parks.tas.gov.au/explore-our-parks/franklin-gordon-wild-rivers-national-park', category: 'Research', scope: 'West Tasmania', ideaIds: ['tas-west'], note: 'Official Lyell Highway, park and alert information.', pinned: false },
  { id: 'hobart-airport', label: 'Hobart Airport destinations', href: 'https://hobartairport.com.au/travellers/destinations/', category: 'Flights', scope: 'Hobart', ideaIds: ['tas-hobart'], note: 'Check current nonstop destinations before fixing the domestic seam.', pinned: true },
  { id: 'great-ocean-official', label: 'Great Ocean Road touring route', href: 'https://www.visitvictoria.com/regions/great-ocean-road/see-and-do/road-trips-and-itineraries/great-ocean-road-touring-route', category: 'Research', scope: 'Great Ocean Road', ideaIds: ['vic-great-ocean'], note: 'Official three-day touring shape and key landscape stops.', pinned: true },
  { id: 'wilsons-parks', label: 'Wilsons Promontory National Park', href: 'https://www.parks.vic.gov.au/places-to-see/parks/wilsons-promontory-national-park', category: 'Research', scope: 'Wilsons Promontory', ideaIds: ['vic-prom'], note: 'Official walks, access, accommodation and alerts.', pinned: false },
  { id: 'sydney-harbour-official', label: 'Sydney Harbour National Park', href: 'https://www.sydney.com/destinations/sydney/sydney-north/manly/attractions/sydney-harbour-national-park', category: 'Research', scope: 'Sydney', ideaIds: ['nsw-sydney'], note: 'Official harbour lookouts, trails and bushland overview.', pinned: true },
  { id: 'sydney-coastal-walks', label: 'Sydney coastal walks', href: 'https://www.sydney.com/things-to-do/nature-and-parks/walks/coastal-walks', category: 'Research', scope: 'Sydney', ideaIds: ['nsw-sydney'], note: 'Compare scenic walk sections without committing to the full routes.', pinned: false },
  { id: 'blue-mountains-parks', label: 'Blue Mountains National Park', href: 'https://www.nationalparks.nsw.gov.au/visit-a-park/parks/blue-mountains-national-park', category: 'Research', scope: 'Blue Mountains', ideaIds: ['nsw-blue'], note: 'Official walks, lookouts and current park alerts.', pinned: true },
  { id: 'royal-parks', label: 'Royal National Park', href: 'https://www.nationalparks.nsw.gov.au/visit-a-park/parks/royal-national-park', category: 'Research', scope: 'Royal National Park', ideaIds: ['nsw-royal'], note: 'Official coast, track, access and alert information.', pinned: false },
  { id: 'natural-earth', label: 'Natural Earth 1:10m map boundary', href: 'https://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-admin-0-countries/', category: 'Map data', scope: 'Whole trip', ideaIds: [], note: 'Public-domain coastline used by the route map.', pinned: false },
  { id: 'photo-perth', label: 'Photo: Perth skyline — Robert Young, CC BY 2.0', href: 'https://commons.wikimedia.org/wiki/File:Perth_skyline.jpg', category: 'Photo credit', scope: 'Perth', ideaIds: ['perth'], note: '', pinned: false },
  { id: 'photo-boranup', label: 'Photo: Boranup Forest — Paulkyranc, CC BY-SA 4.0', href: 'https://commons.wikimedia.org/wiki/File:Karri_trees_-_Boranup_Forest_01.jpg', category: 'Photo credit', scope: 'South West WA', ideaIds: ['margaret-river', 'southern-forests'], note: '', pinned: false },
  { id: 'photo-margaret', label: 'Photo: Margaret River coast — Wikimedia Commons', href: 'https://commons.wikimedia.org/wiki/File:2016_Margaret_River_Australia_-_indian_ocean.jpg', category: 'Photo credit', scope: 'Margaret River', ideaIds: ['margaret-river'], note: '', pinned: false },
  { id: 'photo-albany', label: 'Photo: Albany coast — CSIRO, CC BY 3.0', href: 'https://commons.wikimedia.org/wiki/File:CSIRO_ScienceImage_2482_Coast_near_Albany_Western_Australia.jpg', category: 'Photo credit', scope: 'Albany', ideaIds: ['southern-forests'], note: '', pinned: false },
  { id: 'photo-greens-pool', label: 'Photo: Greens Pool — BaroBert, CC BY-SA 3.0', href: 'https://commons.wikimedia.org/wiki/File:Greens_Pool,_William_Bay,_Denmark_WA.jpg', category: 'Photo credit', scope: 'Denmark & Albany', ideaIds: ['wa-denmark-albany'], note: '', pinned: false },
  { id: 'photo-fitzgerald', label: 'Photo: Fitzgerald River — Bradley Hiller, CC BY-SA 4.0', href: 'https://commons.wikimedia.org/wiki/File:Fitzgerald_River_National_Park,_Western_Australia._Looking_North_East_towards_Thumb_Peak.jpg', category: 'Photo credit', scope: 'Bremer Bay / Fitzgerald River', ideaIds: ['wa-bremer-fitzgerald'], note: '', pinned: false },
  { id: 'photo-wave-rock', label: 'Photo: Wave Rock — Brian W. Schaller, Free Art License', href: 'https://commons.wikimedia.org/wiki/File:A198,_Hyden,_Western_Australia,_Wave_Rock,_2007.JPG', category: 'Photo credit', scope: 'Hyden', ideaIds: ['wa-hyden-return'], note: '', pinned: false },
  { id: 'photo-lucky-bay', label: 'Photo: Lucky Bay — DaHuzyBru, CC BY-SA 4.0', href: 'https://commons.wikimedia.org/wiki/File:Lucky_Bay,_Cape_Le_Grand_National_Park,_January_2025_01.jpg', category: 'Photo credit', scope: 'Esperance', ideaIds: ['esperance'], note: '', pinned: false },
  { id: 'photo-hobart', label: 'Photo: Salamanca Place — Cheng Fei, CC BY-SA 2.0', href: 'https://commons.wikimedia.org/wiki/File:Hobart_Tasmania_Salamanca_Place.jpg', category: 'Photo credit', scope: 'Hobart', ideaIds: ['tas-hobart'], note: '', pinned: false },
  { id: 'photo-hobart-panorama', label: 'Photo: Hobart from Mount Wellington — JJ Harrison, CC BY-SA 3.0', href: 'https://commons.wikimedia.org/wiki/File:Hobart_from_Mount_Wellington_Panorama_1.jpg', category: 'Photo credit', scope: 'Hobart', ideaIds: ['tas-hobart'], note: '', pinned: false },
  { id: 'photo-tasman', label: 'Photo: Cape Huay cliffs — Mooonrise, CC BY-SA 4.0', href: 'https://commons.wikimedia.org/wiki/File:The_spectacular_sea_cliffs_of_Cape_Huay,_Tasman_National_Park,_Tasmania.jpg', category: 'Photo credit', scope: 'Tasman Peninsula', ideaIds: ['tas-peninsula'], note: '', pinned: false },
  { id: 'photo-wineglass', label: 'Photo: Wineglass Bay — JJ Harrison, CC BY-SA 3.0', href: 'https://commons.wikimedia.org/wiki/File:Wineglass_Bay_from_Lookout.jpg', category: 'Photo credit', scope: 'Freycinet', ideaIds: ['tas-east'], note: '', pinned: false },
  { id: 'photo-bay-fires', label: 'Photo: Bay of Fires — Diego Delso, CC BY-SA 3.0', href: 'https://commons.wikimedia.org/wiki/File:Bay_of_Fires-02.jpg', category: 'Photo credit', scope: 'Bay of Fires', ideaIds: ['tas-bay-fires'], note: '', pinned: false },
  { id: 'photo-cataract', label: 'Photo: Cataract Gorge — Thomas Calderbank, CC BY-SA 2.0', href: 'https://commons.wikimedia.org/wiki/File:Cataract_Gorge,_Launceston_in_spring.jpg', category: 'Photo credit', scope: 'Launceston', ideaIds: ['tas-north'], note: '', pinned: false },
  { id: 'photo-stanley', label: 'Photo: Stanley and The Nut — Taspictures, CC0', href: 'https://commons.wikimedia.org/wiki/File:StanleyAndNut.jpg', category: 'Photo credit', scope: 'Stanley', ideaIds: ['tas-stanley'], note: '', pinned: false },
  { id: 'photo-cradle', label: 'Photo: Cradle Mountain — Thennicke, CC BY-SA 4.0', href: 'https://commons.wikimedia.org/wiki/File:Boat_shed_and_Cradle_Mountain_at_Dove_Lake,_Tas.jpg', category: 'Photo credit', scope: 'Cradle Mountain', ideaIds: ['tas-highlands'], note: '', pinned: false },
  { id: 'photo-strahan', label: 'Photo: Strahan — Timox14, CC BY-SA 4.0', href: 'https://commons.wikimedia.org/wiki/File:Strahan,_Tasmania.jpg', category: 'Photo credit', scope: 'West Tasmania', ideaIds: ['tas-west'], note: '', pinned: false },
  { id: 'photo-maria', label: 'Photo: Painted Cliffs — JJ Harrison, CC BY-SA 3.0', href: 'https://commons.wikimedia.org/wiki/File:Painted_Cliffs.jpg', category: 'Photo credit', scope: 'Maria Island', ideaIds: ['tas-maria'], note: '', pinned: false },
  { id: 'photo-lake-st-clair', label: 'Photo: Lake St Clair — Diego Delso, CC BY-SA 3.0', href: 'https://commons.wikimedia.org/wiki/File:Parque_Nacional_Lago_St_Clair-Tasmania-Australia01.JPG', category: 'Photo credit', scope: 'Lake St Clair', ideaIds: ['tas-lake-st-clair-return'], note: '', pinned: false },
  { id: 'photo-melbourne', label: 'Photo: Melbourne and Yarra — Donaldytong, CC BY-SA 3.0', href: 'https://commons.wikimedia.org/wiki/File:Melbourne_Yarra_River.jpg', category: 'Photo credit', scope: 'Melbourne', ideaIds: ['vic-melbourne'], note: '', pinned: false },
  { id: 'photo-gor', label: 'Photo: Twelve Apostles — Dietmar Rabich, CC BY-SA 4.0', href: 'https://commons.wikimedia.org/wiki/File:Princetown_(AU),_Port_Campbell_National_Park,_Twelve_Apostles_--_2019_--_0969.jpg', category: 'Photo credit', scope: 'Great Ocean Road', ideaIds: ['vic-great-ocean'], note: '', pinned: false },
  { id: 'photo-prom', label: 'Photo: Squeaky Beach — Iwanttobeanomad, CC BY-SA 4.0', href: 'https://commons.wikimedia.org/wiki/File:Wilsons_Promontory_National_Park_-_Squeaky_Beach_sunset.jpg', category: 'Photo credit', scope: 'Wilsons Promontory', ideaIds: ['vic-prom'], note: '', pinned: false },
  { id: 'photo-sydney', label: 'Photo: Sydney Harbour — Shiv Travelogue, CC BY-SA 4.0', href: 'https://commons.wikimedia.org/wiki/File:Sydney_Shot.jpg', category: 'Photo credit', scope: 'Sydney', ideaIds: ['nsw-sydney'], note: '', pinned: false },
  { id: 'photo-blue', label: 'Photo: Three Sisters — Dietmar Rabich, CC BY-SA 4.0', href: 'https://commons.wikimedia.org/wiki/File:Blue_Mountains_National_Park_(AU),_Three_Sisters_--_2019_--_1987-9.jpg', category: 'Photo credit', scope: 'Blue Mountains', ideaIds: ['nsw-blue'], note: '', pinned: false },
  { id: 'photo-royal', label: 'Photo: Royal National Park coast — Alex Proimos, CC BY 2.0', href: 'https://commons.wikimedia.org/wiki/File:Bushland,_Royal_National_Park,_The_Coast_Walk,_NSW_Australia_(4045437811).jpg', category: 'Photo credit', scope: 'Royal National Park', ideaIds: ['nsw-royal'], note: '', pinned: false },
]
