const commons = (file) => `https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(file)}`

const photo = (id, file, caption, credit, license, sourceUrl) => ({
  id,
  src: commons(file),
  caption,
  credit,
  license,
  sourceUrl,
})

export const kimberleyIdeas = [
  {
    id: 'wa-kimberley-transit', name: 'Perth → Kununurra flight', routeFrom: 'Perth', routeTo: 'Kununurra', kind: 'flight', region: 'Flight', area: 'Flights & transfers', mapGroup: 'Flights',
    summary: 'A dedicated one-day flight and airport allowance between southern WA and the East Kimberley.', days: 1, status: 'excluded', color: 'flight',
    image: '', coordinates: [128.74, -15.773], mapLabel: 'Perth → Kununurra', hideMapMarker: true, gallery: [],
    highlights: ['Fly between Perth and Kununurra', 'Allow a calendar day for airport and vehicle logistics', 'Confirm the late-season operating day'],
    note: 'Late-October flight frequency may be lower than in the main dry season, so build the direction around confirmed operating days.',
    tradeoffs: 'Flying avoids an impractical multi-day road transfer but creates a second vehicle hire and constrains the route to airline operating days.',
    season: 'Place this module as close as possible to 26 October, before more tours and park facilities finish for the season.',
    rationale: 'A visible one-day block prevents the outbound regional flight from looking like part of a scenic stay.',
  },
  {
    id: 'kimberley-perth-transit', name: 'Kununurra → Perth flight', routeFrom: 'Kununurra', routeTo: 'Perth', kind: 'flight', region: 'Flight', area: 'Flights & transfers', mapGroup: 'Flights',
    summary: 'A dedicated one-day return flight and airport allowance after the East Kimberley road section.', days: 1, status: 'excluded', color: 'flight',
    image: '', coordinates: [115.967, -31.94], mapLabel: 'Kununurra → Perth', hideMapMarker: true, gallery: [],
    highlights: ['Return the Kimberley hire car', 'Allow for airport and baggage time', 'Connect onward from Perth only with a safe margin'],
    note: 'This is a planning allowance, not a cabin-class choice or a confirmed booking.',
    tradeoffs: 'Late-season frequency can constrain the final Kimberley day and onward arrangements.',
    season: 'Confirm the operating date before fixing the last Kununurra night.',
    rationale: 'Separating the return flight keeps the two regional transfers on their true dates.',
  },
  {
    id: 'kimberley-kununurra', name: 'Kununurra & Mirima', region: 'East Kimberley WA', area: 'The Kimberley', mapGroup: 'The Kimberley',
    summary: 'A compact base for glowing sandstone, big-water views and early or late walks.', days: 2, status: 'excluded', color: 'coral',
    image: commons('Mirima National Park.JPG'), coverImageId: 'kimberley-mirima', coordinates: [128.74, -15.773], mapLabel: 'Kununurra',
    highlights: ['Mirima National Park at sunrise or late afternoon', "Kelly's Knob 360-degree sunset view", 'Lily Creek Lagoon, Sleeping Buddha and the Ord irrigation area'],
    note: 'Use Kununurra as the air-conditioned hub for flights and excursions, with walks confined to the cooler ends of the day.',
    tradeoffs: 'Four nights can provide useful weather and heat resilience, but the town itself does not need four full sightseeing days.',
    season: 'October averages about 38°C and November about 39°C; humidity and thunderstorm risk rise quickly.',
    rationale: 'Two touring days cover the town and nearby viewpoints; extra direction days should be treated as flight or weather buffers.',
    gallery: [
      photo('kimberley-mirima', 'Mirima National Park.JPG', 'Sandstone valley in Mirima National Park', 'Steven Marshall / Cardboardbird', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Mirima_National_Park.JPG'),
      photo('kimberley-ord-river', '.00 0982 Ord River - Australia.jpg', 'Ord River near Kununurra', 'W. Bulach', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:.00_0982_Ord_River_-_Australia.jpg'),
    ],
  },
  {
    id: 'kimberley-lake-argyle', name: 'Lake Argyle & the Ord River', region: 'East Kimberley WA', area: 'The Kimberley', mapGroup: 'The Kimberley',
    summary: 'An inland sea among dry ranges, best experienced from the water and at sunset.', days: 2, status: 'excluded', color: 'coral',
    image: commons('00 2098 Western Australia - Lake Argyle.jpg'), coverImageId: 'kimberley-lake-argyle', coordinates: [128.88, -16.15], mapLabel: 'Lake Argyle',
    highlights: ['Late-afternoon or sunset wildlife cruise', 'Dam wall, spillway and Carr Boyd Range views', 'Kayak, approved swim stop and infinity-pool panorama'],
    note: 'Stay beside the lake rather than treating it as a day trip; confirm which cruises still operate after October.',
    tradeoffs: 'The lake is reliably scenic, but the longest Ord River cruise programme is concentrated in the main dry season.',
    season: 'The water remains, but late-season days are extremely hot and some scheduled cruises reduce or stop.',
    rationale: 'Two nights give both evening and morning light without requiring a hurried 150-kilometre return day from Kununurra.',
    gallery: [
      photo('kimberley-lake-argyle', '00 2098 Western Australia - Lake Argyle.jpg', 'Lake Argyle among the East Kimberley ranges', 'W. Bulach', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:00_2098_Western_Australia_-_Lake_Argyle.jpg'),
      photo('kimberley-lake-crocodile', 'Freshwater crocodile at Lake Argyle, Western Australia.jpg', 'Freshwater crocodile at Lake Argyle', 'Wikimedia Commons contributor', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Freshwater_crocodile_at_Lake_Argyle,_Western_Australia.jpg'),
    ],
  },
  {
    id: 'kimberley-purnululu', name: 'Purnululu & the Bungle Bungles', region: 'East Kimberley WA', area: 'The Kimberley', mapGroup: 'The Kimberley',
    summary: 'World Heritage striped domes and immense gorges reached as a demanding high-clearance 4WD excursion.', days: 3, status: 'excluded', color: 'coral',
    image: commons('Bungle Bungles.jpg'), coverImageId: 'kimberley-bungles-aerial', coordinates: [128.4, -17.48], mapLabel: 'Purnululu',
    highlights: ['High-clearance 4WD approach from Kununurra', 'Cathedral Gorge, the Domes and Piccaninny Creek', 'A second park sector only if heat, roads and time permit'],
    note: 'Plan this as a drive only after confirming the park, Spring Creek Track, campground and vehicle-hire conditions immediately before travel.',
    tradeoffs: 'The park is 304 kilometres from Kununurra and the final 53-kilometre 4WD track can take several hours; late-season heat and storms can close access.',
    season: 'The park may remain open into November, weather permitting, but visitor facilities and daily tours are concentrated from April to October.',
    rationale: 'Three days allows the long approach, at least one night near the range and a safer return without pretending this is a Kununurra day trip.',
    gallery: [
      photo('kimberley-bungles-aerial', 'Bungle Bungles.jpg', 'Aerial view of the Bungle Bungle Range', 'Nichollas Harrison', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Bungle_Bungles.jpg'),
      photo('kimberley-domes-walk', 'The Domes Walk, Purnululu National Park.jpg', 'The Domes Walk in Purnululu National Park', 'Graeme Churchard', 'See source page', 'https://commons.wikimedia.org/wiki/File:The_Domes_Walk,_Purnululu_National_Park.jpg'),
    ],
  },
  {
    id: 'kimberley-wyndham-parry', name: 'Wyndham & Parry Lagoons', region: 'East Kimberley WA', area: 'The Kimberley', mapGroup: 'The Kimberley',
    summary: 'Five river systems, gulf-scale viewpoints and a crocodile-safe wetland hide.', days: 1, status: 'excluded', color: 'coral',
    image: commons('Wyndham from five rivers lookout.jpg'), coverImageId: 'kimberley-five-rivers', coordinates: [128.124, -15.486], mapLabel: 'Wyndham',
    highlights: ['Five Rivers Lookout over the Cambridge Gulf', 'Marlgu Billabong bird hide at Parry Lagoons', 'The Grotto and Telegraph Hill if heat and access allow'],
    note: 'Use the sealed highway as the dependable route. Take Parry Creek Road only with a suitable 4WD and a current road report.',
    tradeoffs: 'This is a rewarding 200-kilometre day from Kununurra, but midday heat can make minor stops feel marginal.',
    season: 'Wet-season rain improves the landscape but can flood Parry Creek Road and other unsealed approaches.',
    rationale: 'The Five Rivers panorama adds a large-scale coastal and estuarine landscape missing from the Kununurra and Lake Argyle cards.',
    gallery: [photo('kimberley-five-rivers', 'Wyndham from five rivers lookout.jpg', 'Wyndham from Five Rivers Lookout', 'MissMegido', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Wyndham_from_five_rivers_lookout.jpg')],
  },
  {
    id: 'kimberley-swimming-holes', name: 'Molly Springs & local pools', region: 'East Kimberley WA', area: 'The Kimberley', mapGroup: 'The Kimberley',
    summary: 'A small permanent spring plus conditional late-season waterfall and swimming stops.', days: 1, status: 'excluded', color: 'blue',
    image: commons('Galjiba.jpg'), coverImageId: 'kimberley-molly-springs', coordinates: [128.5, -15.72], mapLabel: 'Molly Springs',
    highlights: ['Permanent shaded pool at Galjiba, Molly Springs', 'The Grotto when current local advice supports swimming', 'Black Rock and Middle Springs only when roads and water quality are suitable'],
    note: 'Never infer crocodile safety from clear water or other swimmers. Confirm every natural-water swim locally on the day.',
    tradeoffs: 'The most dependable pool is small; the dramatic waterfalls need rain, but rain can make their access roads impassable.',
    season: 'Late dry season can mean weak flow or stagnant pools; early wet-season storms can transform conditions within hours.',
    rationale: 'Keep swimming as a flexible local card rather than promising a waterfall circuit that may not exist at the planned dates.',
    gallery: [photo('kimberley-molly-springs', 'Galjiba.jpg', 'Galjiba, Molly Springs', 'Crobe12', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Galjiba.jpg')],
  },
  {
    id: 'kimberley-el-questro', name: 'El Questro & Emma Gorge', region: 'East Kimberley WA', area: 'The Kimberley', mapGroup: 'The Kimberley',
    summary: 'The strongest gorge-and-springs module near Kununurra, but closed before this trip begins.', days: 3, status: 'excluded', color: 'violet',
    image: commons("Emma's Gorge.jpg"), coverImageId: 'kimberley-emma-gorge', coordinates: [127.98, -16.01], mapLabel: 'El Questro',
    highlights: ['Emma Gorge pool and waterfall', 'Zebedee Springs and El Questro Gorge', 'Cockburn Range and Chamberlain Gorge views'],
    note: 'Retain as a comparison card in case dates move earlier; do not include it in the present late-October direction.',
    tradeoffs: 'It would materially improve a September or early-October itinerary, but accommodation and visitor operations normally close around 15 October.',
    season: 'Published 2025 to 2026 closure dates show Emma Gorge and El Questro closing on 15 October.',
    rationale: 'Excluding it explicitly prevents the web app from presenting the classic Kimberley route as achievable on the current dates.',
    gallery: [photo('kimberley-emma-gorge', "Emma's Gorge.jpg", 'The pool beneath the walls of Emma Gorge', 'M.c.c.1999', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Emma%27s_Gorge.jpg')],
  },
  {
    id: 'kimberley-mitchell-falls', name: 'Mitchell Falls', region: 'North Kimberley WA', area: 'The Kimberley', mapGroup: 'The Kimberley',
    summary: 'A four-tiered Kimberley icon that is too seasonal and remote for the present dates.', days: 2, status: 'excluded', color: 'violet',
    image: commons('Mitchell Falls, The Kimberley, Western Australia (7916162022).jpg'), coverImageId: 'kimberley-mitchell-falls', coordinates: [125.6969, -14.8237], mapLabel: 'Mitchell Falls',
    highlights: ['Four-tiered Punamii-unpuu falls', 'Mitchell Plateau escarpments and Livistona palms', 'Best reached by a seasonal flight and helicopter combination'],
    note: 'Keep for a future dry-season Kimberley journey rather than stretching the Kununurra module northwest.',
    tradeoffs: 'Ground access is a major 4WD expedition and flights are costly; by late October the falls may be little more than a trickle.',
    season: 'Best flow is generally May to July. Dry-season access and remote tour bases close as the wet season approaches.',
    rationale: 'It is visually important enough to compare, but marking it excluded keeps the fixed-date plan honest.',
    gallery: [photo('kimberley-mitchell-falls', 'Mitchell Falls, The Kimberley, Western Australia (7916162022).jpg', 'Mitchell Falls in the dry season', 'Travel & Shit', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:Mitchell_Falls,_The_Kimberley,_Western_Australia_(7916162022).jpg')],
  },
]

export const kimberleyDirection = {
  id: 'wa-south-kimberley', name: 'Southern WA + the Kimberley', days: 28, pace: 'Two contrasting WA regions, deliberately buffered',
  transit: 'Return regional flights + two separate WA road sections', image: commons('Bungle Bungles.jpg'),
  summary: 'A two-centre WA trip: a south-coast drive through Esperance first, then a late-season East Kimberley road section.',
  pros: ['Esperance replaces Margaret River', 'Both regional flights have visible calendar days', 'Purnululu is allowed three days for the 4WD journey'],
  order: ['perth', 'southern-forests', 'wa-denmark-albany', 'wa-bremer-fitzgerald', 'esperance', 'wa-hyden-return', 'wa-kimberley-transit', 'kimberley-kununurra', 'kimberley-lake-argyle', 'kimberley-purnululu', 'kimberley-wyndham-parry', 'kimberley-swimming-holes', 'kimberley-perth-transit'],
  choices: {
    perth: ['included', 3], 'southern-forests': ['included', 2], 'wa-denmark-albany': ['included', 3], 'wa-bremer-fitzgerald': ['included', 1], esperance: ['included', 3], 'wa-hyden-return': ['included', 1],
    'wa-kimberley-transit': ['included', 1], 'kimberley-kununurra': ['included', 4], 'kimberley-lake-argyle': ['included', 3],
    'kimberley-purnululu': ['included', 3], 'kimberley-wyndham-parry': ['included', 1], 'kimberley-swimming-holes': ['included', 2], 'kimberley-perth-transit': ['included', 1],
  },
}

export const kimberleyBookmarks = [
  { id: 'kimberley-season-weather', label: 'Kimberley weather and seasons', href: 'https://www.australiasnorthwest.com/plan/weather-climate/', category: 'Research', scope: 'The Kimberley', ideaIds: kimberleyIdeas.map((idea) => idea.id), note: 'Official regional context for the late-October and November wet-season transition.', pinned: true },
  { id: 'kimberley-purnululu-parks', label: 'Purnululu National Park', href: 'https://exploreparks.dbca.wa.gov.au/park/purnululu-national-park', category: 'Research', scope: 'Purnululu', ideaIds: ['kimberley-purnululu'], note: 'Official access, heat, seasonal closure and 4WD-track information.', pinned: true },
  { id: 'kimberley-el-questro-closures', label: 'El Questro seasonal closures', href: 'https://elquestro.com.au/seasonal-closures', category: 'Research', scope: 'El Questro', ideaIds: ['kimberley-el-questro'], note: 'Confirms why El Questro is excluded from the current late-October direction.', pinned: true },
  { id: 'kimberley-kununurra-swimming', label: 'Kununurra swimming guidance', href: 'https://www.visitkununurra.com/faqs', category: 'Safety', scope: 'Kununurra', ideaIds: ['kimberley-swimming-holes', 'kimberley-lake-argyle'], note: 'Local guidance must be checked before every natural-water swim.', pinned: true },
  { id: 'photo-kimberley-mirima', label: 'Photo: Mirima National Park — Steven Marshall, CC BY-SA 4.0', href: 'https://commons.wikimedia.org/wiki/File:Mirima_National_Park.JPG', category: 'Photo credit', scope: 'Kununurra', ideaIds: ['wa-kimberley-transit', 'kimberley-kununurra'], note: '', pinned: false },
  { id: 'photo-kimberley-argyle', label: 'Photo: Lake Argyle — W. Bulach, CC BY-SA 4.0', href: 'https://commons.wikimedia.org/wiki/File:00_2098_Western_Australia_-_Lake_Argyle.jpg', category: 'Photo credit', scope: 'Lake Argyle', ideaIds: ['kimberley-lake-argyle'], note: '', pinned: false },
  { id: 'photo-kimberley-bungles', label: 'Photo: Bungle Bungles aerial — Nichollas Harrison, CC BY-SA 4.0', href: 'https://commons.wikimedia.org/wiki/File:Bungle_Bungles.jpg', category: 'Photo credit', scope: 'Purnululu', ideaIds: ['kimberley-purnululu'], note: '', pinned: false },
  { id: 'photo-kimberley-wyndham', label: 'Photo: Five Rivers Lookout — MissMegido, CC BY-SA 4.0', href: 'https://commons.wikimedia.org/wiki/File:Wyndham_from_five_rivers_lookout.jpg', category: 'Photo credit', scope: 'Wyndham', ideaIds: ['kimberley-wyndham-parry'], note: '', pinned: false },
  { id: 'photo-kimberley-molly', label: 'Photo: Galjiba, Molly Springs — Crobe12, CC BY-SA 4.0', href: 'https://commons.wikimedia.org/wiki/File:Galjiba.jpg', category: 'Photo credit', scope: 'Kununurra swimming holes', ideaIds: ['kimberley-swimming-holes'], note: '', pinned: false },
  { id: 'photo-kimberley-emma', label: 'Photo: Emma Gorge — M.c.c.1999, CC BY-SA 4.0', href: 'https://commons.wikimedia.org/wiki/File:Emma%27s_Gorge.jpg', category: 'Photo credit', scope: 'El Questro', ideaIds: ['kimberley-el-questro'], note: '', pinned: false },
  { id: 'photo-kimberley-mitchell', label: 'Photo: Mitchell Falls — Travel & Shit, CC BY-SA 2.0', href: 'https://commons.wikimedia.org/wiki/File:Mitchell_Falls,_The_Kimberley,_Western_Australia_(7916162022).jpg', category: 'Photo credit', scope: 'Mitchell Falls', ideaIds: ['kimberley-mitchell-falls'], note: '', pinned: false },
]
