const asset = (name) => `${import.meta.env.BASE_URL}images/${name}`

const photo = (id, file, caption, credit, license, sourceUrl) => ({
  id, src: asset(file), caption, credit, license, sourceUrl,
})

const base = {
  region: 'Western Australia',
  area: 'Perth & Western Australia',
  mapGroup: 'Western Australia',
  status: 'excluded',
  color: 'ochre',
}

export const waDeeperIdeas = [
  {
    ...base, id: 'wa-cape-naturaliste', name: 'Cape Naturaliste & Yallingup', days: 3,
    summary: 'Lighthouse headlands, limestone coast, surf coves and a gentle first road-trip base.',
    image: asset('cape-naturaliste.jpg'), coverImageId: 'cape-naturaliste-light', coordinates: [115.0188, -33.537], mapLabel: 'Cape Naturaliste',
    highlights: ['Cape Naturaliste lighthouse and coastal tracks', 'Yallingup, Canal Rocks and Injidup', 'Boranup or a cave as the southbound transition'],
    note: 'Base around Dunsborough or Yallingup rather than treating the Capes as a Margaret River food-and-wine stay. Keep the coast central and use cafés only as weather fallbacks.',
    rationale: 'Three nights absorb the long-haul recovery, give two coast-led days and avoid changing accommodation between nearby headlands.',
    tradeoffs: 'A single northern-Capes base means some backtracking; moving south saves road time but adds another packing day.',
    season: 'Spring wildflowers and long light suit the coast, but wind and swell should decide which side of the cape gets the longer walk.',
    stay: 'Hotel, motel or self-contained studio around Dunsborough/Yallingup. Camping alternatives include Conto, Boranup or Jarrahdene if a night outdoors appeals.',
    access: 'A standard car covers the principal sights. Use the 4x4 only on tracks explicitly permitted by the rental agreement; do not assume beach access is authorised.',
    conditional: 'Choose the exposed lighthouse/coast day for the calmer forecast; keep caves and forest for rain or strong wind.',
    gallery: [
      photo('cape-naturaliste-light', 'cape-naturaliste.jpg', 'Cape Naturaliste lighthouse', 'CSIRO ScienceImage', 'CC BY 3.0', 'https://commons.wikimedia.org/wiki/File:CSIRO_ScienceImage_11593_Cape_Naturaliste_lighthouse_Western_Australia.jpg'),
      photo('cape-boranup', 'boranup-forest.jpg', 'Karri forest at Boranup', 'Paulkyranc', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Karri_trees_-_Boranup_Forest_01.jpg'),
    ],
  },
  {
    ...base, id: 'wa-pemberton-yeagarup', name: 'Pemberton & Yeagarup', days: 2,
    summary: 'Karri forest, dune country and a 4WD excursion to Yeagarup.',
    image: asset('boranup-forest.jpg'), coverImageId: 'pemberton-karri', coordinates: [116.052, -34.444], mapLabel: 'Pemberton & Yeagarup',
    highlights: ['Karri forest drives and short walks', 'Yeagarup dunes and lake', 'A possible guided or self-drive 4WD beach approach'],
    note: 'This is the first deliberately adventurous 4x4 module. Treat Yeagarup as conditional, not as a promise that forces a poor-weather drive.',
    rationale: 'Two nights give one forest/arrival day and one proper Yeagarup window without compressing the onward Denmark drive.',
    tradeoffs: 'Self-driving offers freedom but requires suitable sand experience and written rental permission; a local tour reduces that risk.',
    season: 'Rain can improve the forest but change dune and track conditions. Check park alerts immediately before setting out.',
    stay: 'Hotel/chalet options include Pump Hill, Jaspers or Lake View. Leaning Marri is the practical camping alternative.',
    access: 'Confirm permission for Yeagarup by name. Carry compressor, shovel, traction boards and recovery points; lower tyre pressures only within the vehicle provider’s guidance.',
    conditional: 'If wind, rain or track advice is poor, substitute forest drives, Beedelup Falls or a guided excursion.',
    gallery: [photo('pemberton-karri', 'boranup-forest.jpg', 'Karri forest character', 'Paulkyranc', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Karri_trees_-_Boranup_Forest_01.jpg')],
  },
  {
    ...base, id: 'wa-denmark-william-bay', name: 'Denmark & William Bay', days: 2,
    summary: 'Turquoise coves, granite boulders and a softer pause after the forest.',
    image: asset('greens-pool.jpg'), coverImageId: 'denmark-greens', coordinates: [117.237, -35.023], mapLabel: 'Denmark & William Bay',
    highlights: ['Greens Pool and Elephant Rocks', 'Ocean Beach and Lights Beach', 'Valley of the Giants on the approach if timing works'],
    note: 'Use Denmark for sheltered granite coves and coastal light; it is intentionally separate from Albany’s more exposed headlands.',
    rationale: 'Two nights allow a complete William Bay day plus the Valley of the Giants transition without making either a roadside stop.',
    tradeoffs: 'A longer stay would add relaxed beach time, but Albany and the eastern coast gain more from spare weather days.',
    season: 'Cold fronts can make exposed beaches uncomfortable; Greens Pool often provides the more sheltered option.',
    stay: 'Hotel/B&B options include Windrose, 31 on the Terrace or Floating Forest. Parry Beach is the camping alternative.',
    access: 'Principal sights are sealed-road accessible. Keep the 4x4 for authorised beach access elsewhere rather than seeking tracks merely to use it.',
    conditional: 'Pair Valley of the Giants with the arrival day; save the clearest, least windy period for William Bay.',
    gallery: [photo('denmark-greens', 'greens-pool.jpg', 'Greens Pool, William Bay National Park', 'BaroBert', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Greens_Pool,_William_Bay,_Denmark_WA.jpg')],
  },
  {
    ...base, id: 'wa-albany-torndirrup', name: 'Albany & Torndirrup', days: 2,
    summary: 'Granite platforms, sea cliffs and the Southern Ocean at full scale.',
    image: asset('albany-coast.jpg'), coverImageId: 'albany-southern-ocean', coordinates: [117.883, -35.024], mapLabel: 'Albany & Torndirrup',
    highlights: ['The Gap and Natural Bridge', 'Bald Head or a shorter Torndirrup walk', 'Sheltered bays when the outer coast is too wild'],
    note: 'Albany is the logistics base; Torndirrup is the reason for the card. Keep the longest walk flexible until wind and visibility are clear.',
    rationale: 'Two nights protect a full headland day and avoid squeezing a major walk between the Denmark transfer and the Stirling Range.',
    tradeoffs: 'A third night would improve weather resilience, but the itinerary already carries flexibility in Perth and Esperance.',
    season: 'The exposed peninsula can be very windy. Treat cliff-edge and blowhole areas conservatively in rough weather.',
    stay: 'Hotel/motel choices around Emu Point or central Albany; Cosy Corner East is a simple camping option outside town.',
    access: 'Sealed access covers the primary national-park sights. Choose footwear and walking distance to match wind, rain and daylight.',
    conditional: 'Bald Head only in suitable conditions; use The Gap, Natural Bridge, Middleton Beach or sheltered viewpoints otherwise.',
    gallery: [photo('albany-southern-ocean', 'albany-coast.jpg', 'Southern Ocean coast near Albany', 'CSIRO', 'CC BY 3.0', 'https://commons.wikimedia.org/wiki/File:CSIRO_ScienceImage_2482_Coast_near_Albany_Western_Australia.jpg')],
  },
  {
    ...base, id: 'wa-stirling-range', name: 'Stirling Range', days: 1,
    summary: 'A mountain interlude with Bluff Knoll or a lower walk chosen by the weather.',
    image: asset('stirling-range.jpg'), coverImageId: 'stirling-bluff-knoll', coordinates: [118.25, -34.38], mapLabel: 'Stirling Range',
    highlights: ['Bluff Knoll in a safe weather window', 'Mount Hassell or a shorter alternative', 'A night close to the ranges for an early start'],
    note: 'Drive via Two Peoples Bay, sleep near the range, then walk before continuing to Bremer Bay. The summit is optional; the landscape is not.',
    rationale: 'One overnight creates an early-morning mountain window without turning the range into a long detour.',
    tradeoffs: 'Weather can erase the summit view, and a demanding walk before the Bremer drive may be tiring.',
    season: 'Conditions change quickly and the summit can be cold, wet or windy even in spring. Check alerts and forecast.',
    stay: 'Stirling Range Retreat is the simple roofed base; Moingup Spring offers park camping.',
    access: 'No special 4x4 requirement for the main trailheads. Carry layers, water and turnaround discipline.',
    conditional: 'Use Bluff Knoll only when cloud, wind and rain are acceptable; choose a lower walk or scenic drive otherwise.',
    gallery: [photo('stirling-bluff-knoll', 'stirling-range.jpg', 'Bluff Knoll in the Stirling Range', 'Wikimedia Commons contributor', 'See source page', 'https://commons.wikimedia.org/wiki/Category:Bluff_Knoll')],
  },
  {
    ...base, id: 'wa-bremer-bay', name: 'Bremer Bay', days: 2,
    summary: 'Remote pale-sand beaches and headlands with room for a conditions-led 4x4 day.',
    image: asset('bremer-bay.jpg'), coverImageId: 'bremer-beach', coordinates: [119.3978, -34.3939], mapLabel: 'Bremer Bay',
    highlights: ['Point Henry beaches and headlands', 'Mazzoletti or Blossoms if access is suitable', 'A full beach day without another relocation'],
    note: 'Two nights make Bremer a real base rather than a fuel stop. Beach access and beach camping are separate decisions; do not assume one permits the other.',
    rationale: 'An arrival afternoon plus one complete coastal day is the minimum that justifies the detour.',
    tradeoffs: 'The best tracks depend on wind, sand and vehicle permission; conventional access still provides worthwhile coves.',
    season: 'Choose beaches by wind direction and swell. Spring conditions can shift markedly during one day.',
    stay: 'B&B, resort or caravan-park accommodation in town; Tozer’s is a bush-camp option. Casual beach camping is prohibited within 10 km of Bremer Bay.',
    access: 'Obtain written permission for Mazzoletti and Blossoms. Check local track advice and avoid isolated sand driving without recovery capability.',
    conditional: 'Use the calmer side of Point Henry; substitute sealed-access beaches if tracks are soft or the rental conditions are unclear.',
    gallery: [photo('bremer-beach', 'bremer-bay.jpg', 'Bremer Beach', 'DaHuzyBru', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Bremer_Beach_-_Bremer_Bay,_Western_Australia_-_January_2025_01.jpg')],
  },
  {
    ...base, id: 'wa-fitzgerald-hopetoun', name: 'Fitzgerald River & Hopetoun', days: 1,
    summary: 'Botanical heath, quartzite peaks and an overnight at the eastern edge of Fitzgerald River.',
    image: asset('fitzgerald-river.jpg'), coverImageId: 'fitzgerald-thumb', coordinates: [120.148, -33.95], mapLabel: 'Fitzgerald & Hopetoun',
    highlights: ['East Mount Barren', 'Four Mile Beach and coastal heath', 'A scenic bridge from Bremer Bay to Esperance'],
    note: 'Treat this as a purposeful park day and overnight, not merely a long transit. Keep enough daylight for East Mount Barren.',
    rationale: 'One night breaks the eastward road and positions the following day for Fitzgerald scenery before Esperance.',
    tradeoffs: 'It is still a moving day; a longer Fitzgerald walk would require another night.',
    season: 'Spring wildflowers are a major strength. Check park roads, fire danger and walking conditions.',
    stay: 'Hopetoun motel/chalet, or Four Mile campground for the camping version.',
    access: 'Main eastern-park sights are accessible without speculative beach driving. Confirm any side track before committing.',
    conditional: 'Walk East Mount Barren only with sufficient daylight and safe wind; retain roadside heath and coastal viewpoints as the fallback.',
    gallery: [photo('fitzgerald-thumb', 'fitzgerald-river.jpg', 'Fitzgerald River National Park toward Thumb Peak', 'Bradley Hiller', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Fitzgerald_River_National_Park,_Western_Australia._Looking_North_East_towards_Thumb_Peak.jpg')],
  },
  {
    ...base, id: 'wa-esperance-coast', name: 'Esperance coast', days: 1,
    summary: 'Great Ocean Drive viewpoints and a comfortable base before the national-park days.',
    image: asset('lucky-bay.jpg'), coverImageId: 'esperance-lucky', coordinates: [121.888, -33.861], mapLabel: 'Esperance',
    highlights: ['Great Ocean Drive', 'West Beach, Twilight Cove and Observatory Point', 'Supplies and forecast check before remote beach days'],
    note: 'Use this as the town-based reset: a scenic loop, fuel, food and current local advice before Cape Le Grand and Wharton.',
    rationale: 'One day provides a lower-effort coast circuit and protects the national-park days from arrival logistics.',
    tradeoffs: 'The town coast is less remote than the eastern beaches, but makes the sequence more resilient.',
    season: 'Wind direction determines which coves feel inviting. Water remains cool even on a bright spring day.',
    stay: 'Apartment, holiday unit or Jetty Resort in Esperance. The holiday park is the easier serviced camping option.',
    access: 'The Great Ocean Drive is conventional-road sightseeing. Use the day to confirm current conditions for the 4x4 sectors.',
    conditional: 'Swap this day with Cape Le Grand if the best beach forecast falls immediately after arrival.',
    gallery: [photo('esperance-lucky', 'lucky-bay.jpg', 'Lucky Bay, Cape Le Grand National Park', 'DaHuzyBru', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Lucky_Bay,_Cape_Le_Grand_National_Park,_January_2025_01.jpg')],
  },
  {
    ...base, id: 'wa-cape-le-grand', name: 'Cape Le Grand', days: 1,
    summary: 'Lucky Bay, granite peaks and brilliant water in the trip’s signature national park.',
    image: asset('lucky-bay.jpg'), coverImageId: 'le-grand-lucky', coordinates: [122.16, -33.99], mapLabel: 'Cape Le Grand',
    highlights: ['Lucky Bay and Hellfire Bay', 'Frenchman Peak if conditions suit', 'A possible Lucky Bay camping night'],
    note: 'This is a full park day. Choose the peak or a longer beach sequence rather than attempting every named stop.',
    rationale: 'One complete day, based in Esperance or Lucky Bay, is enough for the strongest landscapes without rushing the road in from Hopetoun.',
    tradeoffs: 'Camping improves dawn and evening light but reduces town convenience and adds another move.',
    season: 'Clear skies do not guarantee calm wind. Granite can be slippery after rain and exposed on the summit route.',
    stay: 'Keep the Esperance hotel, or use one pre-booked night at Lucky Bay for sunset and sunrise access.',
    access: 'Sealed roads reach the principal bays. Only drive on Lucky Bay sand if permitted and conditions are suitable; it is optional, not required.',
    conditional: 'Frenchman Peak only in dry, low-wind conditions; otherwise prioritise Hellfire Bay, Thistle Cove and coastal viewpoints.',
    gallery: [photo('le-grand-lucky', 'lucky-bay.jpg', 'Lucky Bay, Cape Le Grand National Park', 'DaHuzyBru', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Lucky_Bay,_Cape_Le_Grand_National_Park,_January_2025_01.jpg')],
  },
  {
    ...base, id: 'wa-wharton-beach', name: 'Wharton Beach & Duke of Orleans', days: 1,
    summary: 'A luminous eastern beach day with the 4x4 used for access, not as the attraction.',
    image: asset('wharton-beach.jpg'), coverImageId: 'wharton-white-sand', coordinates: [122.5626, -33.9393], mapLabel: 'Wharton Beach',
    highlights: ['Wharton Beach and Duke of Orleans Bay', 'Little Wharton and nearby coves', 'Victoria Harbour only with suitable access and time'],
    note: 'Keep Wharton separate from Cape Le Grand: it earns its own conditions-led day and avoids turning both areas into a checklist.',
    rationale: 'One full out-and-back day from Esperance provides time to choose beaches by wind and explore without a late onward drive.',
    tradeoffs: 'The remote-road commitment is substantial; Victoria Harbour adds further complexity and should remain optional.',
    season: 'Wind and swell matter more than air temperature. Carry water and allow a conservative turnaround time.',
    stay: 'Return to the Esperance base. Camping is possible only where formally permitted and should not be improvised on the beach.',
    access: 'Confirm written rental permission for Wharton and Victoria Harbour. Use local advice, recovery gear and conservative sand-driving decisions.',
    conditional: 'Skip remote extensions if the sand, wind, fuel margin or vehicle terms are doubtful; Wharton itself remains the priority.',
    gallery: [photo('wharton-white-sand', 'wharton-beach.jpg', 'Wharton Beach', 'DaHuzyBru', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Wharton_Beach,_Western_Australia,_January_2025_01.jpg')],
  },
  {
    ...base, id: 'wa-cape-arid', name: 'Cape Arid extension', days: 3,
    summary: 'A genuinely remote eastern extension for empty beaches, heath and Thomas River.',
    image: '', coordinates: [123.16, -33.86], mapLabel: 'Cape Arid',
    highlights: ['Thomas River and coastal heath', 'Tagon coastal trail or shorter walks', 'A remote camping night if conditions and confidence align'],
    note: 'This is deliberately “Maybe”. It is the trip’s honest optional extension, to include only after vehicle terms, park access, weather and appetite for remoteness are settled.',
    rationale: 'Three days are required to make the eastward drive, explore without haste and return toward Esperance/Hyden safely.',
    tradeoffs: 'It adds isolation, fuel planning and another weather dependency. Removing it converts the plan to a comfortable 22-day core.',
    season: 'Road condition, fire danger, wind and rain must all be checked. Facilities are limited and campgrounds may not be bookable.',
    stay: 'Thomas River/Yokinup camping for the full remote version; otherwise keep Esperance as the boundary and omit the extension.',
    access: 'Obtain explicit rental permission for Cape Arid and named tracks. Carry fuel, water, compressor, shovel, traction boards and offline navigation.',
    conditional: 'Include only if park roads are open, the forecast is stable and both travellers want the extra remoteness; otherwise use the days as coast/weather slack.',
    gallery: [],
  },
  {
    ...base, id: 'wa-hyden', name: 'Hyden & Wave Rock', days: 1,
    summary: 'An inland overnight that breaks the return and changes the landscape completely.',
    image: asset('wave-rock.jpg'), coverImageId: 'hyden-wave', coordinates: [118.865, -32.449], mapLabel: 'Hyden',
    highlights: ['Wave Rock in late or early light', 'An inland break after the south coast', 'A manageable final drive to Perth'],
    note: 'Hyden is primarily route geometry with a distinctive landscape bonus. It prevents Esperance-to-Perth becoming one exhausting day.',
    rationale: 'One night is sufficient for the rock and a safe two-stage return to Perth.',
    tradeoffs: 'The inland route is sparse and less varied than the coast; it earns its place by reducing fatigue.',
    season: 'Warm afternoons are possible. Carry water, keep fuel margins and avoid wildlife-heavy dusk driving.',
    stay: 'Wave Rock Hotel or caravan-park accommodation.',
    access: 'No special 4x4 requirement. Treat the long highway distances and wildlife risk as the important logistics.',
    conditional: 'If Cape Arid is removed, these return days can move earlier without changing the route shape.',
    gallery: [photo('hyden-wave', 'wave-rock.jpg', 'Wave Rock near Hyden', 'Brian W. Schaller', 'Free Art License', 'https://commons.wikimedia.org/wiki/File:A198,_Hyden,_Western_Australia,_Wave_Rock,_2007.JPG')],
  },
  {
    ...base, id: 'wa-perth-return', name: 'Perth return & flight buffer', days: 1,
    summary: 'Return the 4x4, reset at a hotel and protect the international departure.',
    image: asset('perth.jpg'), coverImageId: 'perth-return-skyline', coordinates: [115.8605, -31.9505], mapLabel: 'Perth return', hideMapMarker: true, hideFromRoadRoute: true,
    highlights: ['Complete the Hyden-to-Perth drive', 'Return and inspect the rental vehicle', 'Keep one night between the road trip and long-haul flight'],
    note: 'This is deliberate resilience, not spare time. Keep the final Perth night even if the itinerary becomes tempting to extend.',
    rationale: 'One buffer night protects the international flight from road, vehicle-return and fatigue problems.',
    tradeoffs: 'It consumes a scenic day, but is cheaper and calmer than risking a same-day chain from Hyden.',
    season: 'Use daylight for the final drive and vehicle check; airport logistics are easier the following day.',
    stay: 'Novotel Murray Street or another central/airport-convenient hotel; staying with Susannah remains an alternative.',
    access: 'Refuel, clean as required, photograph the vehicle and allow time for any 4x4 inspection at return.',
    conditional: 'If flight timing later proves exceptionally favourable, retain the night anyway unless the preceding route is shortened.',
    gallery: [photo('perth-return-skyline', 'perth.jpg', 'Perth skyline', 'Robert Young', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Perth_skyline.jpg')],
  },
]

const choice = (status, days) => [status, days]

export const waDeeperDirection = {
  id: 'wa-deeper', name: 'WA deeper · south-west loop', days: 25, pace: 'Scenery-first road trip with conditional 4x4 days',
  transit: 'One 4x4 road loop; hotel-led with optional formal camps; one long-haul flight day at each end',
  image: asset('cape-naturaliste.jpg'),
  summary: 'A 22-day Western Australia core from the Capes to Esperance and Hyden, with Cape Arid held as a three-day optional extension.',
  pros: ['Every overnight base and major landscape day is visible', 'Hotels remain the default while selected camps stay possible', '4x4 access is conditional on written permission, weather and track advice'],
  order: ['perth', 'wa-cape-naturaliste', 'wa-pemberton-yeagarup', 'wa-denmark-william-bay', 'wa-albany-torndirrup', 'wa-stirling-range', 'wa-bremer-bay', 'wa-fitzgerald-hopetoun', 'wa-esperance-coast', 'wa-cape-le-grand', 'wa-wharton-beach', 'wa-cape-arid', 'wa-hyden', 'wa-perth-return', 'perth-london-transit'],
  choices: {
    perth: choice('included', 3),
    'wa-cape-naturaliste': choice('included', 3),
    'wa-pemberton-yeagarup': choice('included', 2),
    'wa-denmark-william-bay': choice('included', 2),
    'wa-albany-torndirrup': choice('included', 2),
    'wa-stirling-range': choice('included', 1),
    'wa-bremer-bay': choice('included', 2),
    'wa-fitzgerald-hopetoun': choice('included', 1),
    'wa-esperance-coast': choice('included', 1),
    'wa-cape-le-grand': choice('included', 1),
    'wa-wharton-beach': choice('included', 1),
    'wa-cape-arid': choice('maybe', 3),
    'wa-hyden': choice('included', 1),
    'wa-perth-return': choice('included', 1),
    'perth-london-transit': choice('included', 1),
  },
}

export const waDeeperBookmarks = [
  { id: 'wa-naturaliste-official', label: 'Cape Naturaliste and Leeuwin-Naturaliste', href: 'https://exploreparks.dbca.wa.gov.au/park/leeuwin-naturaliste-national-park', category: 'Research', scope: 'Cape Naturaliste & Yallingup', ideaIds: ['wa-cape-naturaliste'], note: 'Official park access, alerts and facilities.', pinned: true },
  { id: 'wa-yeagarup-official', label: 'Yeagarup', href: 'https://exploreparks.dbca.wa.gov.au/site/yeagarup', category: 'Logistics', scope: 'Pemberton & Yeagarup', ideaIds: ['wa-pemberton-yeagarup'], note: 'Official access, facilities and current park information.', pinned: true },
  { id: 'wa-valley-giants-official', label: 'Valley of the Giants Tree Top Walk', href: 'https://exploreparks.dbca.wa.gov.au/site/valley-giants-tree-top-walk', category: 'Research', scope: 'Denmark & William Bay', ideaIds: ['wa-denmark-william-bay'], note: 'Opening and access information for the southbound transition.', pinned: false },
  { id: 'wa-william-bay-deep', label: 'William Bay National Park', href: 'https://exploreparks.dbca.wa.gov.au/park/william-bay-national-park', category: 'Research', scope: 'Denmark & William Bay', ideaIds: ['wa-denmark-william-bay'], note: 'Official access, closures and facilities.', pinned: true },
  { id: 'wa-torndirrup-official', label: 'Torndirrup National Park', href: 'https://exploreparks.dbca.wa.gov.au/park/torndirrup-national-park', category: 'Research', scope: 'Albany & Torndirrup', ideaIds: ['wa-albany-torndirrup'], note: 'Official park walks, alerts and access.', pinned: true },
  { id: 'wa-stirling-official', label: 'Stirling Range National Park', href: 'https://exploreparks.dbca.wa.gov.au/park/stirling-range-national-park/', category: 'Research', scope: 'Stirling Range', ideaIds: ['wa-stirling-range'], note: 'Official walking, safety and alert information.', pinned: true },
  { id: 'wa-bremer-beaches', label: 'Bremer Bay beaches', href: 'https://bremerbaybeaches.com.au/things-to-do/', category: 'Research', scope: 'Bremer Bay', ideaIds: ['wa-bremer-bay'], note: 'Local beach descriptions; verify track conditions separately.', pinned: false },
  { id: 'wa-bremer-camping', label: 'Bremer Bay accommodation and camping rules', href: 'https://www.jerramungup.wa.gov.au/visit/where-to-stay/Accommodation-Camping.aspx', category: 'Logistics', scope: 'Bremer Bay', ideaIds: ['wa-bremer-bay'], note: 'Official shire guidance, including the beach-camping restriction near town.', pinned: true },
  { id: 'wa-fitzgerald-deep', label: 'Fitzgerald River National Park', href: 'https://exploreparks.dbca.wa.gov.au/park/fitzgerald-river-national-park', category: 'Research', scope: 'Fitzgerald River & Hopetoun', ideaIds: ['wa-fitzgerald-hopetoun'], note: 'Official access, walks, alerts and camping.', pinned: true },
  { id: 'wa-esperance-beaches', label: 'Esperance beaches guide', href: 'https://www.esperance.wa.gov.au/documents/1711/esperance-beaches-guide', category: 'Research', scope: 'Esperance coast', ideaIds: ['wa-esperance-coast', 'wa-wharton-beach'], note: 'Shire guide to beach access and conditions.', pinned: true },
  { id: 'wa-cape-le-grand-official', label: 'Cape Le Grand National Park', href: 'https://exploreparks.dbca.wa.gov.au/park/cape-le-grand-national-park', category: 'Research', scope: 'Cape Le Grand', ideaIds: ['wa-cape-le-grand'], note: 'Official park, camping, alerts and access information.', pinned: true },
  { id: 'wa-cape-arid-official', label: 'Cape Arid National Park', href: 'https://exploreparks.dbca.wa.gov.au/park/cape-arid-national-park', category: 'Logistics', scope: 'Cape Arid extension', ideaIds: ['wa-cape-arid'], note: 'Essential current access, campground and alert check before including the extension.', pinned: true },
  { id: 'photo-cape-naturaliste', label: 'Photo: Cape Naturaliste lighthouse - CSIRO, CC BY 3.0', href: 'https://commons.wikimedia.org/wiki/File:CSIRO_ScienceImage_11593_Cape_Naturaliste_lighthouse_Western_Australia.jpg', category: 'Photo credit', scope: 'Cape Naturaliste', ideaIds: ['wa-cape-naturaliste'], note: '', pinned: false },
  { id: 'photo-bremer-beach', label: 'Photo: Bremer Beach - DaHuzyBru, CC BY-SA 4.0', href: 'https://commons.wikimedia.org/wiki/File:Bremer_Beach_-_Bremer_Bay,_Western_Australia_-_January_2025_01.jpg', category: 'Photo credit', scope: 'Bremer Bay', ideaIds: ['wa-bremer-bay'], note: '', pinned: false },
  { id: 'photo-wharton-beach', label: 'Photo: Wharton Beach - DaHuzyBru, CC BY-SA 4.0', href: 'https://commons.wikimedia.org/wiki/File:Wharton_Beach,_Western_Australia,_January_2025_01.jpg', category: 'Photo credit', scope: 'Wharton Beach', ideaIds: ['wa-wharton-beach'], note: '', pinned: false },
]
